"""JS/TS: `NPM` → `ts/`, via `aspect_rules_js` + `aspect_rules_ts` / `npm_translate_lock`
(§3.3, §7.5).

The destination root is `ts/` and not `js/` because what lands there is the *source* tree and
this fleet's JavaScript is TypeScript; the emitted `ts_project` is the rule that produces the
`.js`. Nothing outside this file knows either string (§13 row 33).
"""

from __future__ import annotations

import json
import posixpath
from collections.abc import Mapping, Sequence
from fnmatch import fnmatch
from typing import ClassVar, Final

from fleet.ecosystems.base import (
    EcosystemAdapter,
    join_segments,
    register,
    select_entrypoint,
    target_name,
)
from fleet.models.build import (
    BuildTarget,
    BuildUnit,
    InternalDep,
    Resolution,
    SupportFile,
    ToolchainRequirement,
    WorkspaceDep,
)
from fleet.models.enums import ContractKind, Ecosystem
from fleet.models.repo import Coordinate

_PNPM_LOCK_FILE: Final = "pnpm-lock.yaml"
_PNPM_WORKSPACE_FILE: Final = "pnpm-workspace.yaml"
_PACKAGE_JSON_FILE: Final = "package.json"
_BAZELIGNORE_FILE: Final = ".bazelignore"
_TSCONFIG_FILE: Final = "tsconfig.json"
_TSCONFIG_TARGET: Final = "tsconfig"

_NPM_PACKAGE_TARGET: Final = "pkg"
"""The name `npm_translate_lock` expects a first-party package's target to have.

Not a convention this harness chose: `npm_translate_lock.npm_package_target_name` defaults to
`"pkg"`, and the generated store is `_npm_local_package_store(src = "//<dir>:pkg", …)` for a
`link:<dir>` entry. Get the name wrong and Bazel reports `no such target '//ts/acme/lib:pkg'`
from a file nobody in this repository wrote."""

_NODE_MODULES_TARGET: Final = "node_modules"
"""The name `npm_link_all_packages()` is given — in the ROOT package **and in every importer's
own package** — and therefore the second segment of every external label this adapter emits:
`//<dest>:node_modules/<pkg>`.

`@npm//:<pkg>` — what the base class's maven-shaped `@<repo>//:<name>` produced — names nothing.
The `npm_translate_lock` hub's own root package declares `noop`, `sync` and
`exports_files(["defs.bzl"])` and no packages at all; the *importable* targets are the links
`npm_link_all_packages()` creates, and it creates them **per pnpm importer**: with one importer
per JS repo (ADR-0048) the link a `ts/acme/app` target depends on is declared in `ts/acme/app`
and is `//ts/acme/app:node_modules/left-pad`. Real Bazel's answer to the `@npm//:left-pad`
spelling was "no such target '@@aspect_rules_js++npm+npm//:left-pad': target 'left-pad' not
declared in package ''"; its answer to a root-package spelling of a per-importer link is the
same message about `package ''`."""

_PNPM_LOCK: Final = f"//:{_PNPM_LOCK_FILE}"
"""ONE lockfile at the monorepo root, not one per package: `npm_translate_lock` builds a single
`@npm` repository for the whole workspace, and a second lock would give two packages two
different resolutions of the same dependency with no MVS step to notice. One *file* is not one
*importer* — the file this names is a pnpm **workspace** lock carrying one `importers:` entry
per JS repo (ADR-0048), which is how two repos keep two different specifiers inside one lock.

The label and the file are spelled from ONE constant (D10). They were two independent strings in
two phases that never spoke, and the phase that names the file was not the phase that would have
had to create it — so nothing created it, and real Bazel failed inside `npm_translate_lock`."""

_BAZELIGNORE: Final = f"//:{_BAZELIGNORE_FILE}"
"""`verify_node_modules_ignored` is rules_js checking that Bazel is not walking `node_modules`.
It reads the file, so the file has to be there — and unlike the lock this one is not the repo's:
`.bazelignore` is Bazel's own root config and did not exist in any source repo."""

_EMPTY_PNPM_LOCK: Final = (
    "# GENERATED BY fleet — this is the FLOOR, not a resolution; no resolver produced it.\n"
    "lockfileVersion: '9.0'\n"
    "\n"
    "settings:\n"
    "  autoInstallPeers: true\n"
    "  excludeLinksFromLockfile: false\n"
)
"""A parseable, EMPTY pnpm lock — the floor, and deliberately a poor one. `npm_translate_lock`
over it produces an `@npm` repository with no packages in it, so a build that reached this text
fails at the first `//<dest>:node_modules/…` label rather than resolving something plausible
and wrong.

It is no longer what any JS fleet gets: `resolution()` runs pnpm over the declared dependencies
and produces a real one, and `workspace_files()` no longer offers a carry that could skip it.
This stays as the floor a *resolver-less* build would fall to, and it says so in its first line —
the observed failure it produced was "target 'left-pad' not declared in package ''", the
ruleset's message about our file."""

_RESOLVER: Final[tuple[str, ...]] = (
    "pnpm",
    "install",
    "--lockfile-only",
    "--ignore-scripts",
)
"""pnpm resolving the declared dependencies into a real `pnpm-lock.yaml`.

`--lockfile-only` is the whole point: it resolves and writes the lock without materializing a
`node_modules` tree, which is what rules_js is going to do hermetically anyway. `--ignore-scripts`
because a resolution must not execute a package's install hooks on the harness's host — the
monorepo's own build-allowlist is `allowBuilds: {}`, and a resolver that ran what the build
refuses to run would be resolving a different package set than the one Bazel installs."""


def _npm_package_name(coordinate: Coordinate) -> str:
    """`(@acme, ui)` → `@acme/ui`; `("", left-pad)` → `left-pad`.

    The registry name, reassembled from the scope `manifests/npm.py` split off. It is what the
    lockfile keys on and what `npm_link_all_packages()` names its link after, so this is the ONE
    spelling that has to survive the round trip through `Coordinate`.
    """
    return f"{coordinate.group}/{coordinate.name}" if coordinate.group else coordinate.name


def _needs_npm_hub(unit: BuildUnit) -> bool:
    """Whether this unit references the `@npm` hub at all — the ONE gate for every part of it.

    True for a unit with an external dependency (it has a registry package to link) and for one
    with a linkable sibling (it has a `link:` entry to link), because those are the two kinds of
    row that end up in the same lockfile and are materialized by the same
    `npm_link_all_packages()`. Spelled once and read by `workspace_deps`, `workspace_files`,
    `root_targets` and `resolution`, because a unit that emits the `npm_translate_lock` tag but
    no lockfile — or a lockfile but no macro at the root — fails inside the ruleset with a
    message about our file.
    """
    return bool(unit.external_coordinates or _first_party(unit))


def _first_party(unit: BuildUnit) -> list[InternalDep]:
    """The unit's sibling repos that can be linked as npm packages, ordered by `dest`.

    "Can be" is `published is not None`: `npm_translate_lock` links a first-party package under
    its **registry name**, and a sibling that publishes no coordinate has none. Such a sibling is
    not dropped — the driver's plain `//<dest>:<name>` label is still in `dep_labels()` — it
    simply cannot become a `node_modules` entry, which is the honest outcome rather than a link
    named after a directory.
    """
    return sorted(
        (dep for dep in unit.internal_deps if dep.published is not None), key=lambda d: d.dest
    )


def _all_first_party(units: Sequence[BuildUnit]) -> list[InternalDep]:
    """Every linkable sibling of every contributing unit, deduped by `dest` and ordered by it.

    The union half of `_first_party`, for the resolve that runs once per ecosystem: two repos in
    the fleet may link the same sibling, and the root manifest holds ONE `link:` entry per
    package while the resolver's scratch tree holds ONE manifest per directory. `dest` is the
    identity for both, so it is the dedupe key here — stripped, because that is the form both the
    `link:` specifier and the sibling's input **path** are spelled in, and two entries for one
    path is a file staged twice.

    Ordered by the same `dest` `_first_party` sorts on, and the tie-break is total (`label`, then
    the published coordinate) so the winner for a repeated `dest` does not depend on which unit
    the caller listed first — §11.6 requires the same plan to render the same bytes, and the units
    reach this method in whatever order the driver grouped them.
    """
    ordered = sorted(
        (dep for unit in units for dep in _first_party(unit)),
        key=lambda d: (
            d.dest,
            d.label,
            d.published.key if d.published is not None else "",
            (d.published.version_spec or "") if d.published is not None else "",
        ),
    )
    deduped: dict[str, InternalDep] = {}
    for dep in ordered:
        deduped.setdefault(dep.dest.strip("/"), dep)
    return list(deduped.values())


def _importer_dests(units: Sequence[BuildUnit]) -> list[str]:
    """Every pnpm *importer* directory this fleet's JS units imply, deduped and sorted.

    Two kinds of directory, one list, because both hold a `package.json` the resolver reads and
    both therefore owe a `packages:` entry and a `.bazelignore` line (ADR-0048):

    * each unit that references the `@npm` hub at all, which is the repo whose own dependencies
      the importer records — this is the half that stops `[app ms@^2.0.0, report ms@^2.1.3]` from
      collapsing to one specifier;
    * each **linkable sibling**, because pnpm resolves a `link:` specifier by reading the
      manifest at that directory and a directory holding a manifest inside the workspace is an
      importer whether or not the sibling declared a dependency of its own.

    A unit that references the hub in neither way is deliberately absent: it contributes no
    manifest, so listing it would point `packages:` at a directory with nothing in it.
    """
    dests = {unit.dest.strip("/") for unit in units if _needs_npm_hub(unit)}
    dests |= {dep.dest.strip("/") for dep in _all_first_party(units)}
    return sorted(dests)


def _link_specifier(importer_dest: str, sibling_dest: str) -> str:
    """The `link:` specifier an importer at `importer_dest` must write for `sibling_dest`.

    **Importer-relative, and that is measured, not assumed.** pnpm resolves `link:` against the
    directory of the manifest that declares it. Handed `{"@acme/lib": "link:ts/acme/lib"}` in
    `ts/acme/app/package.json`, real pnpm 10.16.1 answers `WARN Installing a dependency from a
    non-existent directory: …/ts/acme/app/ts/acme/lib` and writes a lock whose
    `version: link:ts/acme/lib` rules_js then reads as `paths.normalize(paths.join(import_path,
    link))` = `ts/acme/app/ts/acme/lib` (`npm/private/pnpm.bzl`'s
    `_convert_pnpm_v9_importer_dependency_map`) — a Bazel package that does not exist. The
    root-relative spelling was correct only while the root was the ONE importer.

    `link:../../../ts/acme/lib` and `workspace:*` were both measured to record the identical
    `version: link:../lib`, so the protocol choice is free and ADR-0046's `link:` stands.
    """
    return f"link:{posixpath.relpath(sibling_dest, importer_dest)}"


def _sibling_package_json(dep: InternalDep) -> str:
    """The floor manifest for a linkable sibling that shipped no `package.json` of its own.

    Named after the sibling's published coordinate and not after its directory: pnpm records the
    link under the name it reads out of the manifest, and `npm_link_all_packages()` then creates
    `node_modules/<that name>` — so a floor named `lib` would link `@acme/lib` under `lib` and
    the consumer's `import … from '@acme/lib'` would still not resolve.
    """
    coordinate = dep.published
    payload = {
        "name": _npm_package_name(coordinate) if coordinate is not None else dep.dest,
        "version": (coordinate.version_spec if coordinate else None) or "0.0.0",
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def _root_package_json() -> str:
    """The pnpm **workspace root** manifest: a name, a version, `private`, and NO dependencies.

    The root is an importer like any other, and the one thing it must not be is the fleet's
    dependency dumping ground. The flat map this replaces was keyed on package name and unioned
    over every unit, so it *overwrote in place*: `[app ms@^2.0.0, report ms@^2.1.3]` emitted
    `{"ms": "^2.1.3"}` and `^2.0.0` was gone with no error, the surviving specifier being nothing
    more meaningful than the lexicographically largest (ADR-0048). Each repo's declarations now
    live in that repo's own `<dest>/package.json`, which is the only place they can be kept
    apart.

    `private` because a workspace root is never published, and it is what stops pnpm warning
    about a root manifest with no `license`/`repository`.
    """
    payload = {"name": "monorepo", "version": "0.0.0", "private": True}
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def _unit_package_json(unit: BuildUnit) -> str:
    """ONE JS repo's importer manifest: **its own** registry dependencies and **its own** links.

    This is the file that preserves what the flat union destroyed. pnpm records
    `specifier:` verbatim per importer — three importers declaring `ms@^2.0.0`, `ms@^2.1.3` and
    an exact `ms@2.0.0` were measured to keep all three, with `2.0.0` and `2.1.3` coexisting in
    `packages:` under distinct integrity hashes (ADR-0048). An honest limit stated with it: pnpm
    still dedupes *within* a satisfiable range, so `^2.0.0` beside `^2.1.3` resolves to `2.1.3`.
    What multi-importer buys is that no repo's declaration is silently overwritten by another's,
    not that every repo gets its own resolved version.

    The external half is synthesized rather than carried, and that is not a shortcut: the repo's
    own `package.json` names its siblings with registry specifiers (`"@acme/lib": "^1.4.0"`),
    which resolve to nothing on npm — pnpm would fail, or worse, find an unrelated public package
    of that name.

    The first-party half is D12's fix and is the whole of "how one TypeScript package in this
    monorepo imports another": each sibling is declared with pnpm's **`link:` protocol**, so the
    resolved lock carries `'@acme/lib': {specifier: link:../lib, version: link:../lib}` in THIS
    repo's importer. `npm_translate_lock` reads that entry, generates a first-party package store
    whose `src` is `//ts/acme/lib:pkg`, and this repo's own `npm_link_all_packages()`
    materializes it at `//<dest>:node_modules/@acme/lib` — so `tsc` resolves
    `import … from '@acme/lib'` by walking `node_modules`, exactly as it would outside Bazel.
    Without the entry the specifier resolves to nothing and the consumer fails with
    `error TS2307: Cannot find module '@acme/lib'`.

    The manifest's `name` is the repo's **published** registry name where it has one, because a
    sibling links under the name pnpm reads out of the manifest at the linked directory; the
    sanitized target name is the floor for a unit that publishes nothing, since a `dest` with
    slashes in it is not a legal npm name at all.

    Sorted keys and a trailing newline because this text is an input to a lockfile that is
    committed onto the integration branch: two runs must produce the same bytes (§11.6).
    """
    dest = unit.dest.strip("/")
    published = unit.published
    dependencies = {
        _npm_package_name(coordinate): coordinate.version_spec or "*"
        for coordinate in sorted(
            unit.external_coordinates, key=lambda c: (c.key, c.version_spec or "")
        )
    }
    dependencies.update(
        {
            _npm_package_name(dep.published): _link_specifier(dest, dep.dest.strip("/"))
            for dep in _first_party(unit)
            if dep.published is not None
        }
    )
    payload = {
        "name": _npm_package_name(published) if published is not None else target_name(unit),
        "version": (published.version_spec if published is not None else None) or "0.0.0",
        "private": True,
        "dependencies": dict(sorted(dependencies.items())),
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def _pnpm_workspace_text(importers: Sequence[str]) -> str:
    """`pnpm-workspace.yaml`: one `packages:` entry per importer, plus the build allowlist.

    The `packages:` list is what MAKES the importers importers — pnpm resolves a workspace, and a
    directory holding a `package.json` that no member glob covers is a directory pnpm never
    reads. It is spelled as explicit paths and not as a glob so the file states exactly the set
    `_importer_dests` computed: a glob would silently pick up a directory some later phase
    creates, and the `.bazelignore` lines beside it would then be one short.

    `allowBuilds: {}` is unchanged and keeps its own reason. `npm_translate_lock` REFUSES to
    evaluate without an explicit build-allowlist: "pnpm 'allowBuilds' (or 'onlyBuiltDependencies'
    in pnpm < 10.26) configuration required". It is a mapping and not a list — a list gets
    `'list' value has no field or method 'items'` from `npm_translate_lock_state.bzl` — and `{}`
    is the honest value: *no* package may run a lifecycle hook in this monorepo until someone
    decides otherwise, which is also the safe default for code being migrated. The file is not
    NAMED by any tag, so nothing in the module text points at it; it is required by the ruleset
    all the same, which is precisely why the knowledge lives on the adapter that names the
    extension rather than anywhere a generic file-reference walk could find it (§13 row 6).
    """
    listed = (
        "packages: []\n"
        if not importers
        else "packages:\n" + "".join(f"  - {dest}\n" for dest in importers)
    )
    return (
        "# GENERATED BY fleet — the monorepo's pnpm workspace: one package per JS importer.\n"
        f"{listed}"
        "allowBuilds: {}\n"
    )


def _bazelignore_text(importers: Sequence[str]) -> str:
    """`.bazelignore`: the root `node_modules` **and one `<dest>/node_modules` line per importer**.

    Mandatory, and read off the ruleset rather than reasoned about:
    `npm_translate_lock_helpers.bzl`'s `_find_missing_bazel_ignores` computes
    `paths.normalize(paths.join(root_package, importer, "node_modules"))` for **every** importer
    path and fails the repository rule for each one it cannot find. A bare `node_modules` line
    does NOT cover `ts/acme/app/node_modules`: the check is an exact string match against the
    normalized lines, so the file owes one line per importer the moment the lock has more than
    the root one.
    """
    lines = ["node_modules", *(f"{dest}/node_modules" for dest in importers)]
    return "".join(f"{line}\n" for line in lines)

_DEFAULT_TSCONFIG: Final = (
    '{\n'
    '  "compilerOptions": {\n'
    '    "declaration": true,\n'
    '    "target": "es2022",\n'
    '    "module": "esnext",\n'
    '    "moduleResolution": "bundler"\n'
    "  }\n"
    "}\n"
)
"""`declaration: true` mirrors what `generate_targets` sets on the `ts_project`: a library emitted
without declarations makes every consumer fail with "could not find a declaration file", and the
two halves of that setting disagreeing is a failure that reads as the consumer's bug."""


@register
class JsAdapter(EcosystemAdapter):
    """`ts/<scope>/<name>`; `npm_translate_lock` for external deps."""

    name: ClassVar[str] = "js"
    ecosystems: ClassVar[frozenset[Ecosystem]] = frozenset({Ecosystem.NPM})
    monorepo_dir: ClassVar[str] = "ts"
    ruleset: ClassVar[str | None] = "aspect_rules_js"
    extension: ClassVar[str | None] = "npm.npm_translate_lock"
    extension_bzl: ClassVar[Mapping[str, str]] = {
        # Both read off the rulesets: aspect_rules_js ships `npm` in `npm/extensions.bzl`, and
        # aspect_rules_ts ships its toolchain extension under the bare name `ext` in
        # `ts/extensions.bzl`. `ext` is also the proxy variable, because `use_extension` takes
        # the extension's own symbol — a prettier local name is a `no such symbol` error.
        "npm": "@aspect_rules_js//npm:extensions.bzl",
        "ext": "@aspect_rules_ts//ts:extensions.bzl",
    }
    repo_name: ClassVar[str | None] = "npm"
    library_rule: ClassVar[str] = "ts_project"
    binary_rule: ClassVar[str | None] = "js_binary"
    test_rule: ClassVar[str | None] = "js_test"
    library_bzl: ClassVar[str | None] = "@aspect_rules_ts//ts:defs.bzl"
    binary_bzl: ClassVar[str | None] = "@aspect_rules_js//js:defs.bzl"
    test_bzl: ClassVar[str | None] = "@aspect_rules_js//js:defs.bzl"
    entrypoints: ClassVar[tuple[str, ...]] = ("main.ts", "index.ts", "cli.ts", "server.ts")
    src_suffixes: ClassVar[tuple[str, ...]] = (".ts", ".tsx", ".mts", ".cts", ".json")
    """What `ts_project` compiles, plus the `.json` it resolves (`tsconfig`, `resolveJsonModule`).
    A `package.json` left in `srcs` is not a compilation input and a `.md` is not either."""
    contract_bindings: ClassVar[Mapping[ContractKind, str]] = {
        ContractKind.PROTO: "ts_proto_library",
        ContractKind.OPENAPI: "genrule",
        ContractKind.SHARED_LIB: "ts_project",
        # No AVRO/THRIFT key: there is no maintained Bazel rule that generates TypeScript from
        # either IDL. §13 row 31 makes that a `ContractBindingUnavailable` finding on the
        # consumer, which is the truth; a rule name invented here would be a BUILD file that
        # fails to load and a finding nobody ever files.
    }

    def path_tail(self, coordinate: Coordinate) -> str:
        """`<scope>/<name>` — `@acme/ui` → `acme/ui`, `react` → `react`.

        `Coordinate.group_path` has already dropped the `@`, which is deliberate: `@` is legal in
        an npm scope and illegal in a Bazel package path, and keeping the scope as a *directory*
        is what stops `@acme/ui` and `@corp/ui` from both wanting `ts/ui`.
        """
        return join_segments(coordinate.group_path, coordinate.name)

    def import_specifier(self, coordinate: Coordinate, dest: str) -> str:
        """The npm package name — `@acme/lib` — **unchanged by the migration**, and that is the
        point.

        A cross-repo TypeScript import is a module specifier, and rules_js resolves a first-party
        package under the same registry name it had before the move: the sibling becomes a
        `link:` entry in the consumer's importer of the root `pnpm-lock.yaml`,
        `npm_link_all_packages()` materializes it at `//<dest>:node_modules/@acme/lib`, and `tsc`
        finds it by walking `node_modules` exactly as `pnpm` would have.
        So the correct rewrite of `from '@acme/lib'` is `from '@acme/lib'`
        — the specifier survives — and the Bazel label that stood here instead was not a
        mis-spelling of it but a category error: `error TS2307: Cannot find module
        '//ts/acme/lib:lib' or its corresponding type declarations`.

        `dest` is not consulted for that reason: the destination is where the package *lands*,
        never how it is *named*. It is in the signature because other languages (a Go module
        path) do read it.
        """
        _ = dest
        return _npm_package_name(coordinate)

    def external_labels(self, unit: BuildUnit) -> list[str]:
        """`//<dest>:node_modules/<pkg>` — the label `npm_link_all_packages()` actually declares
        **in this unit's own package**.

        rules_js does not expose npm packages as targets of the hub repository. The hub's root
        package declares `noop`, `sync` and `exports_files(["defs.bzl"])`; what a `ts_project`
        depends on is a *link*, created by `npm_link_all_packages()` in a Bazel package that is
        the pnpm root **or a workspace importer** (`npm_translate_lock_generate.bzl` gates the
        macro on exactly that). With one importer per JS repo (ADR-0048) this repo's links live
        in this repo's package, so the label carries `unit.dest`. The root spelling
        `//:node_modules/<pkg>` was correct only while the root was the one importer, and under a
        workspace it resolves to nothing for every package no root importer declared — which is
        the `no such target '//:node_modules/ms': target 'node_modules/ms' not declared in
        package ''` this change closes.

        Overridden here rather than in `WorkspaceDep.label` for the reason `PyAdapter` overrides
        it: the shape is per-ruleset dialect, and `@maven//:guava`, `@pypi//requests` and
        `//ts/acme/app:node_modules/left-pad` are three different answers to one question (§7.2).
        """
        dest = unit.dest.strip("/")
        return sorted(
            {
                f"//{dest}:{_NODE_MODULES_TARGET}/{_npm_package_name(dep.coordinate)}"
                for dep in self.workspace_deps(unit)
            }
        )

    def root_targets(self, unit: BuildUnit) -> list[BuildTarget]:
        """`npm_link_all_packages()` in the monorepo root — what makes the virtual store exist.

        **It stays even though no label points into the root package any more**, and that is not
        a leftover: `npm_translate_lock_generate.bzl` emits every package *store* under
        `if is_root:`, so the root call is what materializes the thing each importer's own links
        resolve *through*. Without it the per-importer labels are `no such target
        '//:.aspect_rules_js/node_modules/left-pad@1.3.0'` — the store, named from the root
        package, by a macro nobody called. `visibility` is left empty because the macro does not
        take one — the links it creates are public by construction, and passing the attribute is
        a load error.

        The importer half of the same decision is in `generate_targets()`, because it belongs in
        the unit's own `BUILD.bazel` rather than in the root's.

        Gated on `_needs_npm_hub`, like every other reference to the `@npm` hub: a unit with
        neither an external dependency nor a linkable sibling emits no `npm_translate_lock` tag,
        so there is no `@npm` to load `defs.bzl` from and the macro call would be an
        unknown-repository error at the root.
        """
        if not _needs_npm_hub(unit):
            return []
        return [
            BuildTarget(
                package="",
                name=_NODE_MODULES_TARGET,
                rule="npm_link_all_packages",
                load_from="@npm//:defs.bzl",
                visibility=[],
            )
        ]

    def resolution(self, units: Sequence[BuildUnit]) -> Resolution | None:
        """pnpm resolving the declared dependencies into a lock with a real `packages:` section.

        **This is the file `npm_translate_lock` was being handed a header for.** The floor is a
        parseable lock with `settings:` and nothing else, so the `@npm` hub it builds contains no
        packages — not even the direct dependency — and the first `//<dest>:node_modules/left-pad`
        in any generated `ts_project` fails. Nothing in this harness can *reconstruct* a lock, and
        under ADR-0048 nothing may carry one either (a workspace resolution is not any one repo's
        lock); what it can do is run the resolver that produces one.

        **The scratch tree is the monorepo's own shape: a pnpm WORKSPACE with one importer per
        JS repo** (ADR-0048). The root `package.json` carries no dependencies at all; each
        importer's `<dest>/package.json` carries that repo's own, and `pnpm-workspace.yaml` lists
        every one of them. That is what makes the resolved lock keep each repo's `specifier:`
        verbatim instead of collapsing the fleet onto one name-keyed map in which the last writer
        wins.

        **Each linkable sibling contributes its own `package.json` as an input**, at its monorepo
        path inside the scratch directory. That is not decoration: pnpm resolves a `link:<dir>`
        specifier by *reading the manifest at that directory*, and without it the resolver exits
        non-zero naming a path — which `_run_resolution` reports as a `DependencyResolutionError`
        rather than writing a lock with the sibling missing. A sibling that is itself a unit of
        this resolve gets the synthesized importer manifest above (its real one names *its*
        siblings with registry specifiers that resolve to nothing on npm); a sibling that is not
        gets its real manifest carried, with the floor naming the package so that a sibling which
        shipped none still resolves to the right name instead of to the directory's.

        **One resolve over every JS unit, not one per repo.** The lock is `//:pnpm-lock.yaml` —
        one file, one virtual store — so a per-repo resolve produces N candidate locks for one
        path and whichever the driver writes first is the only one that survives. The gate is
        therefore `any(...)`: a unit with neither an external dependency nor a linkable sibling
        contributes nothing to the workspace but must not veto the resolve for the units beside
        it.
        """
        importers = _importer_dests(units)
        if not importers:
            return None
        manifests: dict[str, SupportFile] = {
            f"{dep.dest.strip('/')}/{_PACKAGE_JSON_FILE}": SupportFile(
                path=f"{dep.dest.strip('/')}/{_PACKAGE_JSON_FILE}",
                carry_from=[f"{dep.dest.strip('/')}/{_PACKAGE_JSON_FILE}"],
                content=_sibling_package_json(dep),
            )
            # Deduped by `dest` — which IS the path — because two units linking the same sibling
            # would otherwise stage two `SupportFile`s for one file in the resolver's scratch
            # tree. A unit's own manifest overwrites the sibling floor below, never the reverse.
            for dep in _all_first_party(units)
        }
        for unit in sorted(units, key=lambda u: u.dest.strip("/")):
            if not _needs_npm_hub(unit):
                continue
            path = f"{unit.dest.strip('/')}/{_PACKAGE_JSON_FILE}"
            manifests[path] = SupportFile(path=path, content=_unit_package_json(unit))
        return Resolution(
            lock_path=_PNPM_LOCK_FILE,
            argv=list(_RESOLVER),
            inputs=[
                SupportFile(path=_PACKAGE_JSON_FILE, content=_root_package_json()),
                # Synthesized, never carried: this file describes the workspace the resolver is
                # being asked to resolve — the monorepo's importers at their monorepo paths — and
                # the repo's own `pnpm-workspace.yaml` describes its packages at their old ones.
                # Carrying it would resolve a workspace that does not exist here.
                SupportFile(
                    path=_PNPM_WORKSPACE_FILE, content=_pnpm_workspace_text(importers)
                ),
                *(manifests[path] for path in sorted(manifests)),
            ],
        )

    def workspace_deps(self, unit: BuildUnit) -> list[WorkspaceDep]:
        """`npm_translate_lock` over the root pnpm lock — the whole npm surface at once.

        Unlike `maven.install`, this dialect names no versions: the lockfile is the resolution,
        so every coordinate renders the identical tag and `render_module_bazel` collapses them
        to one. The per-coordinate rows survive because `BuildTarget.deps` needs a label per
        dependency and `external_labels()` derives one from each row.

        **The first-party siblings are rows here too**, and that is what taking the `BuildUnit`
        bought (D12). It is not a fiction that they are "workspace deps": `npm_translate_lock`
        translates ONE lockfile whose importer for this repo holds both the registry packages and
        the `link:` entries, and `npm_link_all_packages()` materializes both kinds under
        `//<dest>:node_modules/<name>`. Emitting only the external half is what made
        `external_labels()` structurally unable to name a sibling, so a `ts_project` was left
        depending on `//ts/acme/lib:lib` — a target that supplies the declarations to the action
        and no `node_modules` entry for `tsc` to resolve the specifier through.
        """
        coordinates = [
            *unit.external_coordinates,
            *(dep.published for dep in _first_party(unit) if dep.published is not None),
        ]
        return [
            WorkspaceDep(
                ruleset="aspect_rules_js",
                extension="npm.npm_translate_lock",
                coordinate=coordinate,
                repo_name="npm",
                attrs={
                    "name": "npm",
                    "pnpm_lock": _PNPM_LOCK,
                    "verify_node_modules_ignored": _BAZELIGNORE,
                },
            )
            for coordinate in sorted(coordinates, key=lambda c: c.key)
        ]

    def workspace_files(self, units: Sequence[BuildUnit]) -> list[SupportFile]:
        """The root files `npm_translate_lock` needs before it will evaluate (D10).

        **Fleet-wide over every JS unit, not per repo**, and here that is load bearing rather
        than a dedupe: all three files state a fact about the FLEET and not about the unit that
        names them (ADR-0048). `pnpm-workspace.yaml`'s `packages:` list must name every importer
        and `.bazelignore` owes one `<dest>/node_modules` line per importer, so a per-unit view
        renders different bytes for one root path in every repo and the driver's union keeps
        exactly one of them — which is how a root file that must describe the whole monorepo ends
        up describing one repo. They are computed once, from `_importer_dests(units)`, and every
        unit of the ecosystem is handed the identical set.

        **The lock is neither carried nor invented: it is RESOLVED.** A `pnpm-lock.yaml` is a
        resolution of the whole dependency graph including transitive versions and integrity
        hashes, and nothing in this harness can reconstruct one — so `content` stays a parseable
        empty floor and `resolution()` is what actually produces the file. `carry_from` is
        **dropped**, and that is the second half of the same defect: with ≥1 importer the root
        lock is a resolution of the *workspace*, which no single repo's lock is, so promoting one
        repo's single-package lock to the root would describe a monorepo that does not exist —
        and, because the driver's carry short-circuit skips the resolver entirely, would do it
        without any resolver ever running. This is `models/build.py`'s documented
        `carry_from` → `Resolution` → `content` precedence selecting the MIDDLE term, which is
        exactly the case that precedence exists for; the repo's own lock is not lost, Phase 2
        left it at `<dest>/pnpm-lock.yaml`.

        `pnpm-workspace.yaml` and `.bazelignore` drop their `carry_from` for the same reason and
        one more: both are Bazel/pnpm *workspace* configuration for a workspace no source repo
        has ever seen, so a repo's own copy of either describes its old layout at its old paths.
        """
        importers = _importer_dests(units)
        if not importers:
            return []
        return [
            SupportFile(path=_PNPM_LOCK_FILE, content=_EMPTY_PNPM_LOCK),
            SupportFile(path=_PNPM_WORKSPACE_FILE, content=_pnpm_workspace_text(importers)),
            SupportFile(path=_BAZELIGNORE_FILE, content=_bazelignore_text(importers)),
        ]

    def package_files(self, unit: BuildUnit) -> list[SupportFile]:
        """`<dest>/tsconfig.json` — the file the `:tsconfig` target below compiles against.

        Carried FROM ITSELF: a repo that shipped a `tsconfig.json` already has it at this exact
        path, because relocation moved the whole tree — so naming the path as its own `carry_from`
        candidate is what makes materializing it a no-op instead of a clobber. `content` is the
        floor for a repo that shipped none, which would otherwise leave
        `ts_config(src = "tsconfig.json")` naming a file nobody wrote.
        """
        path = f"{unit.dest.strip('/')}/{_TSCONFIG_FILE}"
        return [SupportFile(path=path, carry_from=[path], content=_DEFAULT_TSCONFIG)]

    def generate_targets(self, unit: BuildUnit) -> list[BuildTarget]:
        """One `ts_project` over the package's sources, plus a `js_binary` iff it has an entry.

        `declaration = True` is not cosmetic: a downstream `ts_project` type-checks against its
        deps' `.d.ts`, so a library emitted without declarations makes every consumer's build
        fail with "could not find a declaration file" — a failure that reads as the consumer's
        bug and is fixed here.
        """
        name = target_name(unit)
        deps = self.dep_labels(unit)
        # The tsconfig is the COMPILER's input, not a compilation unit: it reaches the rule
        # through the `tsconfig` attribute and the `ts_config` target below. Leaving it in `srcs`
        # as well (`.json` is an accepted suffix) would declare one file twice, in two roles.
        srcs = [path for path in self.sources(unit) if path != _TSCONFIG_FILE]
        attrs: dict[str, str | int | bool | list[str]] = {
            "declaration": True,
            "tsconfig": f":{_TSCONFIG_TARGET}",
            "transpiler": "tsc",
        }
        # `data`, not `srcs`: `ts_project` compiles what it is given, so a `package.json` or a
        # `.md` in `srcs` is either a compile error or a file `tsc` silently ignores — and
        # dropping it instead loses a file the package reads at runtime.
        data = self.non_source_files(unit)
        if data:
            attrs["data"] = data
        targets = [
            BuildTarget(
                package=unit.dest,
                name=name,
                rule="ts_project",
                load_from="@aspect_rules_ts//ts:defs.bzl",
                srcs=srcs,
                deps=deps,
                attrs=attrs,
            ),
            # D10: `tsconfig = ":tsconfig"` above is a label into this very package, and until
            # this target existed it named nothing — every generated TS package failed to load
            # with "no such target '//<dest>:tsconfig'". The target is emitted here, beside the
            # reference, because the two are one decision: an adapter that names a label owes the
            # target, exactly as it owes the file `package_files()` declares.
            BuildTarget(
                package=unit.dest,
                name=_TSCONFIG_TARGET,
                rule="ts_config",
                load_from="@aspect_rules_ts//ts:defs.bzl",
                attrs={"src": _TSCONFIG_FILE},
            ),
        ]
        if _needs_npm_hub(unit):
            # ADR-0048's importer half: this repo is a pnpm workspace project, so the links its
            # own `ts_project` depends on — `//<dest>:node_modules/<pkg>` — are declared HERE and
            # nowhere else. `npm_translate_lock_generate.bzl` gates the macro on the calling
            # package being the pnpm root *or* an importer and `fail()`s otherwise, so this call
            # and the `<dest>` in `external_labels()` are one decision: emit the labels without
            # the macro and every one of them is "no such target". The root call stays too
            # (`root_targets()`), because the stores the links resolve through are emitted under
            # `if is_root:`. `visibility` is empty because the macro does not take one.
            targets.append(
                BuildTarget(
                    package=unit.dest,
                    name=_NODE_MODULES_TARGET,
                    rule="npm_link_all_packages",
                    load_from="@npm//:defs.bzl",
                    visibility=[],
                )
            )
        if _PACKAGE_JSON_FILE in self.sources(unit):
            # D12: the target a `link:` entry in the lockfile resolves to. `ts_project` alone is
            # not enough and the difference is only visible inside a sandbox: linking a
            # `ts_project` directly stages its *declarations* and not its `package.json`, so
            # `tsc` finds the directory and no manifest in it, and answers the consumer with
            # "Cannot find module '@acme/lib'" about a link that exists. `npm_package` collects
            # the package as ONE directory artifact — the manifest included — which is what
            # makes a first-party link resolvable the way a registry package is.
            #
            # `package.json` is named explicitly beside `:{name}` because it is a *source* of
            # this package, not an output of the `ts_project`: `ts_project` compiles `.ts` and
            # passes the rest through as data, and the JsInfo the store consumes carries the
            # compilation outputs.
            targets.append(
                BuildTarget(
                    package=unit.dest,
                    name=_NPM_PACKAGE_TARGET,
                    rule="npm_package",
                    load_from="@aspect_rules_js//npm:defs.bzl",
                    srcs=[f":{name}", _PACKAGE_JSON_FILE],
                )
            )
        entry = select_entrypoint(srcs, self.entrypoints)
        if entry is not None:
            targets.append(
                BuildTarget(
                    package=unit.dest,
                    name=f"{name}_bin",
                    rule="js_binary",
                    load_from="@aspect_rules_js//js:defs.bzl",
                    # NO `deps` (D7): `js_binary` is a rules_js *runtime* rule and has no such
                    # attribute — real Bazel rejects the target outright with "no such attribute
                    # 'deps' in 'js_binary' rule", which `bazel query` never sees because the
                    # attribute is only checked when the rule is instantiated. `data` is where
                    # the edge belongs and is not a weaker statement of it: `data` collects the
                    # `ts_project`'s JsInfo, so the library's own `deps` — the internal labels
                    # and the `@npm//:…` links — are in the binary's runfiles transitively.
                    # Dropping the edge instead of moving it would produce a binary that
                    # analyses and dies at `bazel run` with MODULE_NOT_FOUND.
                    attrs={"entry_point": _js_output(entry), "data": [f":{name}"]},
                )
            )
        return targets

    def test_targets(self, unit: BuildUnit) -> list[BuildTarget]:
        """A `ts_project` compiling the test sources, plus a `js_test` running the compiled entry
        point via `data` — D112's JS slice (round VI task 87).

        **Two defects, not one, both unreachable until `test_srcs` had a real predicate feeding
        it (round VI task 87 widened `TEST_SRC_PARTITIONED_ECOSYSTEMS` to `NPM` in the same
        change).** `docs/INTEGRATION_HONESTY.md`'s `**D7 — FIXED, by deletion.**` entry found and
        fixed `js_binary`'s
        `deps=` — a `rules_js` *runtime* rule has no such attribute — and this method reused the
        identical wrong shape one function up, unexercised (`test_srcs` was always `()`). That
        precedent transfers directly: `js_test` shares `js_binary`'s `_ATTRS` base (`js_test =
        rule(attrs = dict(js_binary_lib.attrs, **{"env_inherit": ..., "_lcov_merger": ...,
        "_coverage_report": ...}))`, verified against the pinned `aspect_rules_js@3.4.0` tag's
        `js/private/js_binary.bzl`), so `deps` is absent from `js_test` for the exact same reason.

        **But `srcs` was ALSO wrong, and D7's fix never had to face it.** `js_binary`/`js_test`'s
        shared `_ATTRS` has no `srcs` attribute either — verified against the same source — so
        `BuildTarget(srcs=test_srcs, ...)` would have rendered a second nonexistent attribute
        (`generators.py::render_target` emits `srcs = [...]` unconditionally whenever the list is
        non-empty) and real Bazel would refuse the target with "no such attribute 'srcs' in
        'js_test' rule" the moment it tried to instantiate it, one attribute past where the
        `deps=` fix alone would have landed. **And unlike `js_binary`'s entry point — one of the
        UNIT's own `srcs`, already compiled by the unit's own `:{name}` `ts_project` — a test file
        is never compiled by anything: `unit.test_srcs` is disjoint from `unit.srcs`
        (`cli._partition_test_srcs`), so `:{name}`'s `ts_project` never sees it.** `js_test`'s
        `entry_point` names a `.js` file, so something has to transpile the `.ts` test source
        first. The fix is therefore a second `ts_project` — `{name}_test_lib`, `testonly=True`,
        `srcs=test_srcs`, depending on the unit's own library (for the module under test) and its
        external labels (for whatever the test imports from `@npm`) — mirroring exactly what
        `generate_targets()`'s `js_binary` already does for the unit's own entry point, just for
        the test file's compilation instead of assuming one already exists.

        **The entry point is the `.js` the transpiler emits, never a path off disk, and never a
        file `ts_project` does not compile.** `js_test` runs Node: point it at TypeScript and you
        get a green `bazel build` and a test target that cannot start — the warning this docstring
        carried before round VI task 87 and which that task's own rewrite dropped, restored here
        because the fix round below found the failure had come back by a wider door.

        **`_test_entry_point`, not `test_srcs[0]` (round VI task 87 review, fix round 1).** Taking
        the first element was measured wrong, not merely arbitrary: `package_relative` SORTS, and
        `_` (0x5F) sorts before `s` (0x73), so in any repo carrying a `__tests__/` directory the
        first element is deterministically the alphabetically-first file in THAT directory — a
        fixture or a helper, essentially never the test. The reproduction that prompted this was a
        generated `js_test(entry_point = "__tests__/fixture.json")`: a target real Bazel ANALYSES
        green (the label resolves — it is a real source file) and which `bazel test` cannot start,
        which is why `--nobuild` analysis, the proof this method's fix originally shipped with,
        is structurally blind to it. So the selection now requires a compiled `.ts(x)` and prefers
        a `*.test.*`/`*.spec.*` basename — Jest's own convention, the same one `cli._is_js_test_src`
        applies on the way in. The two are deliberately NOT one shared constant: `cli.py` imports
        only `ecosystems.base` and never a concrete adapter (§12.6/ADR-0100's confinement), so a
        shared literal would have to cross that boundary; instead each states the convention and
        `test_targets()` re-derives it from its OWN input rather than trusting the partitioner.

        Still only ONE `js_test` per unit — a "one `js_test` per file" redesign stays out of
        scope, exactly as task 86's Rust brief scoped an analogous question out of ITS fix. Every
        discovered test file is still compiled (`{name}_test_lib`'s `srcs` keeps the whole list),
        so a multi-file suite analyses correctly; only the selected file is *run*.
        """
        test_srcs = self.test_sources(unit)
        if not test_srcs:
            return []
        entry = _test_entry_point(test_srcs)
        if entry is None:
            # Nothing compilable to name as `entry_point`, so there is no runnable `js_test` to
            # emit and emitting one anyway is precisely the green-build/dead-test failure above.
            # Unreachable from the driver — `cli._is_js_test_src` only routes `.ts(x)` here — so
            # this is a guard on a direct caller, not a path the fleet's own walk produces, and
            # the sources stay in `srcs`/`data` where the un-partitioned unit already had them.
            return []
        name = target_name(unit)
        test_lib_name = f"{name}_test_lib"
        return [
            BuildTarget(
                package=unit.dest,
                name=test_lib_name,
                rule="ts_project",
                load_from="@aspect_rules_ts//ts:defs.bzl",
                srcs=test_srcs,
                deps=[f":{name}", *self.external_labels(unit)],
                # `declaration: True` mirrors the library `ts_project` above, and here it is not
                # only consistency: `aspect_rules_ts`'s own `ts_project` macro (verified against
                # the pinned `aspect_rules_ts@3.10.0` tag's `ts/defs.bzl`) auto-emits a HIDDEN
                # `<name>_typecheck_test` `build_test` target whenever declaration emission is
                # off, which this adapter never asked for and which a `bazel build //<dest>/...`
                # would then also analyse — verified live: dropping `declaration` here (leaving it
                # at the rule's default `False`) makes a real `bazel build --nobuild //<dest>/...`
                # try to resolve `widgets_test_lib_typecheck_test`, a target this adapter's own
                # `BuildTarget` list never named.
                attrs={
                    "declaration": True,
                    "tsconfig": f":{_TSCONFIG_TARGET}",
                    "transpiler": "tsc",
                },
                testonly=True,
                visibility=["//visibility:private"],
            ),
            BuildTarget(
                package=unit.dest,
                name=f"{name}_test",
                rule="js_test",
                load_from="@aspect_rules_js//js:defs.bzl",
                # NO `deps`, NO `srcs` (D7, widened): `js_test` shares `js_binary`'s `_ATTRS` base
                # and neither attribute exists on it. `data` is where the compiled test's JsInfo
                # (and, transitively through it, the library's own JsInfo) belongs — exactly the
                # `js_binary` shape above, pointed at the test compile unit instead of the unit's
                # own primary target.
                attrs={
                    "entry_point": _js_output(entry),
                    "data": [f":{test_lib_name}"],
                },
                testonly=True,
                visibility=["//visibility:private"],
            ),
        ]

    def toolchain_requirements(self) -> list[ToolchainRequirement]:
        """The TypeScript compiler version, which `aspect_rules_ts` requires be declared: its
        extension has no default, so an unregistered `ts_version` is a MODULE.bazel that does not
        evaluate at all."""
        return [
            ToolchainRequirement(
                ruleset="aspect_rules_ts",
                extension="ext.deps",
                name="typescript",
                version="5.6.3",
                attrs={"ts_version": "5.6.3"},
                # `ext.deps` creates `@npm_typescript`, and a repo the root module never
                # `use_repo`s is invisible: every `ts_project` resolves its compiler through it,
                # so without this line the whole package is `no such package '@@[unknown repo
                # 'npm_typescript' requested from @@]//'`. Which repos a tag creates is
                # per-ruleset knowledge, so it is declared by the adapter that names the
                # extension rather than guessed by the renderer (§13 row 6).
                repo_names=["npm_typescript"],
            )
        ]


def _js_output(src: str) -> str:
    """`src/main.ts` → `src/main.js`: the file `ts_project` emits for a TypeScript source.

    Returns a NON-TypeScript path unchanged, which is why `_test_entry_point` below has to filter
    on the suffix rather than leaning on this: handed `__tests__/fixture.json` this answers
    `__tests__/fixture.json`, and a `js_test` naming it analyses green and cannot start.
    """
    if src.endswith((".ts", ".tsx")):
        return src.rsplit(".", maxsplit=1)[0] + ".js"
    return src


_TEST_ENTRY_GLOBS: Final = ("*.test.ts", "*.test.tsx", "*.spec.ts", "*.spec.tsx")
"""Jest's own default `testMatch` basenames — the same convention `cli._is_js_test_src` applies
when it decides what enters `unit.test_srcs`, restated here rather than shared because `cli.py`
imports only `ecosystems.base` and never a concrete adapter (§12.6/ADR-0100). Restating it is the
cost of that boundary; `_test_entry_point` re-derives from its own input so the two can only
disagree about which file RUNS, never about correctness of the emitted target."""


def _test_entry_point(test_srcs: Sequence[str]) -> str | None:
    """The one test source whose compiled `.js` becomes the `js_test`'s `entry_point`.

    Two filters, in order, and the FIRST is the load-bearing one (round VI task 87 review, fix
    round 1): the entry must be something `ts_project` actually transpiles, or `_js_output` hands
    back the source path unchanged and the `js_test` names a file Node cannot execute. Among the
    compilable ones, a Jest-convention basename wins over source order, because source order is
    `package_relative`'s SORT and `_` (0x5F) < `s` (0x73) — so `__tests__/anything.ts` would
    otherwise always beat `src/thing.test.ts`, making a helper the test binary's entry point.

    `None` when nothing compilable is present; the caller emits no `js_test` rather than a target
    that analyses green and dies at `bazel test`.
    """
    compilable = [src for src in test_srcs if src.endswith((".ts", ".tsx"))]
    if not compilable:
        return None
    named = [
        src
        for src in compilable
        if any(fnmatch(src.rsplit("/", 1)[-1], glob) for glob in _TEST_ENTRY_GLOBS)
    ]
    return (named or compilable)[0]
