"""Python: `PYPI` → `py/`, via `rules_python` / `pip.parse` (§3.3, §7.5)."""

from __future__ import annotations

import re
from collections.abc import Mapping, Sequence
from typing import ClassVar, Final

from fleet.ecosystems.base import (
    EcosystemAdapter,
    native_test_unit_count,
    path_segment,
    register,
    select_entrypoint,
    target_name,
)
from fleet.models.build import (
    BuildTarget,
    BuildUnit,
    NativeBaseline,
    Resolution,
    SupportFile,
    ToolchainRequirement,
    WorkspaceDep,
)
from fleet.models.enums import ContractKind, Ecosystem
from fleet.models.repo import Coordinate

_PYTHON_VERSION: Final = "3.12"
"""The interpreter `pip.parse` resolves wheels for and `python.toolchain` registers. One
constant, used by both, because a hub built for 3.12 wheels and a toolchain running 3.11 is a
build that fails at import time with a message about neither."""

_REQUIREMENTS_LOCK: Final = "requirements.lock"
"""The root file `pip.parse` reads, as a PATH. `//:{_REQUIREMENTS_LOCK}` is the label, and the
two are spelled from one constant so the file this adapter creates and the file it names cannot
drift apart — which is the whole of defect D10 in one line."""

_CARRIED_REQUIREMENTS: Final[tuple[str, ...]] = ("requirements.lock", "requirements.txt")
"""A real, resolved requirements file the repo already ships, preferred over anything derived.
Ordered: an actual lock beats a loose requirements list, which beats what we can infer."""

_REQUIREMENTS_IN: Final = "requirements.in"
"""The resolver's INPUT: the declared specs, one per line. Named `requirements.in` because the
name reaches the output — `uv pip compile` annotates each root distribution `# via -r
requirements.in` — so a different name here silently rewrites every lockfile in the monorepo."""

_RESOLVER: Final[tuple[str, ...]] = (
    "uv",
    "pip",
    "compile",
    _REQUIREMENTS_IN,
    "--output-file",
    _REQUIREMENTS_LOCK,
    "--python-version",
    _PYTHON_VERSION,
    "--no-header",
    "--quiet",
)
"""`uv pip compile` — the resolver whose output `pip.parse` was always being handed a stand-in for.

Every flag is load-bearing:

* `--python-version` is `_PYTHON_VERSION`, the SAME constant `pip.parse` and `python.toolchain`
  use. A closure resolved for one interpreter and installed under another is a build that fails
  at import time with a message about neither.
* `--no-header` suppresses uv's `# This file was autogenerated by uv via the following command:`
  banner, which embeds the **absolute output path** — a scratch directory keyed by run id and
  repo. With it, two runs of the same fleet write two different files for the same resolution and
  §11.6's "the same plan renders the same bytes" is false for a reason no offline test can see.
* `--quiet` keeps the resolver's progress chatter out of a `stderr_tail` that is evidence.

`uv` rather than `pip-compile`: it is the resolver installed here, it needs no virtualenv of the
target interpreter to resolve for it, and its output is the same annotated pip requirements format
`pip.parse` already parses."""

_NON_ALNUM = re.compile(r"[-_.]+")


@register
class PyAdapter(EcosystemAdapter):
    """`py/<distribution>`; `pip.parse` for external deps."""

    name: ClassVar[str] = "py"
    ecosystems: ClassVar[frozenset[Ecosystem]] = frozenset({Ecosystem.PYPI})
    monorepo_dir: ClassVar[str] = "py"
    ruleset: ClassVar[str | None] = "rules_python"
    extension: ClassVar[str | None] = "pip.parse"
    extension_bzl: ClassVar[Mapping[str, str]] = {
        # Read off rules_python 1.0.0 itself: `python/extensions/{pip,python}.bzl` each re-export
        # the extension from `python/private/`. There is no `//:extensions.bzl` in this ruleset —
        # the guessed one made every MODULE.bazel we shipped fail to load.
        "pip": "@rules_python//python/extensions:pip.bzl",
        "python": "@rules_python//python/extensions:python.bzl",
    }
    repo_name: ClassVar[str | None] = "pypi"
    library_rule: ClassVar[str] = "py_library"
    binary_rule: ClassVar[str | None] = "py_binary"
    test_rule: ClassVar[str | None] = "py_test"
    library_bzl: ClassVar[str | None] = "@rules_python//python:defs.bzl"
    binary_bzl: ClassVar[str | None] = "@rules_python//python:defs.bzl"
    test_bzl: ClassVar[str | None] = "@rules_python//python:defs.bzl"
    entrypoints: ClassVar[tuple[str, ...]] = ("__main__.py", "main.py", "cli.py", "app.py")
    src_suffixes: ClassVar[tuple[str, ...]] = (".py", ".py3")
    """Exactly what `py_library` accepts, quoting its own refusal: "is misplaced here (expected
    .py or .py3)". A `pyproject.toml` in `srcs` fails ANALYSIS, so the package does not build at
    all — it is not a warning, and it is not something a later phase recovers from."""
    contract_bindings: ClassVar[Mapping[ContractKind, str]] = {
        ContractKind.PROTO: "py_proto_library",
        ContractKind.OPENAPI: "genrule",
        ContractKind.SHARED_LIB: "py_library",
        # No AVRO/THRIFT: the maintained Bazel rules for both stop at the JVM. §13 row 31.
    }

    def path_tail(self, coordinate: Coordinate) -> str:
        """`<distribution>`, PEP 503-normalized — `Flask_SQLAlchemy` and `flask-sqlalchemy` are
        the *same* distribution to PyPI, so they must not become two directories that Phase 1's
        collision audit then reports as two repos contesting one name.

        The group is deliberately dropped: PyPI has no namespace, so a group here would be
        inventing one and moving the package out from under the name pip installs it by.
        """
        return path_segment(_NON_ALNUM.sub("-", coordinate.name.strip()))

    def import_specifier(self, coordinate: Coordinate, dest: str) -> str:
        """The importable top-level module: the distribution name with `-`/`.` folded to `_`.

        `acme-lib-py` is installed and imported as `acme_lib_py`, and it keeps that name in the
        monorepo because `py_library`/`py_binary` carry `imports = ["."]` — the package directory
        is on `sys.path`, so `from acme_lib_py import normalize` resolves exactly as it did
        before the move. A distribution whose top-level module differs from its name (`PyYAML` →
        `yaml`) is not derivable from a `Coordinate` and is precisely what a `RewriteRule` in
        `config/rules/` is for; what this must never return is a Bazel label, which `import`
        cannot parse at all.
        """
        _ = dest
        return _NON_ALNUM.sub("_", coordinate.name.strip()).lower()

    def external_labels(self, unit: BuildUnit) -> list[str]:
        """`@pypi//<normalized>` — the label rules_python's hub actually declares.

        The base class spells every external dep `@<repo>//:<name>`, which is what
        `rules_jvm_external`'s `@maven` looks like and is **not** what a `pip.parse` hub looks
        like. rules_python gives each distribution its own package inside the hub, so real Bazel
        answers `no such target '@@rules_python++pip+pypi//:requests': target 'requests' not
        declared in package ''; however, a source directory of this name exists` — the hub is
        fine, the *label shape* was wrong. Overridden here and not in `WorkspaceDep.label`
        because the shape is per-ruleset dialect, which is the adapter's to know (§7.2).

        Normalisation is rules_python's own (`[-._]+` → `_`, lower-cased), not `path_tail`'s:
        the directory the hub creates for `charset-normalizer` is `charset_normalizer`, and a
        label spelled with the dash resolves to nothing.
        """
        return sorted(
            {
                f"@{dep.repo_name}//{_NON_ALNUM.sub('_', dep.coordinate.name.strip()).lower()}"
                for dep in self.workspace_deps(unit)
            }
        )

    def workspace_deps(self, unit: BuildUnit) -> list[WorkspaceDep]:
        """`pip.parse` over one root requirements lock — the hub every `@pypi//<pkg>` resolves in.

        Version-free by dialect: the lock is the resolution. `pip.parse` against a range would
        re-resolve on every host and make two runs of the same fleet build different wheels.
        """
        return [
            WorkspaceDep(
                ruleset="rules_python",
                extension="pip.parse",
                coordinate=coordinate,
                repo_name="pypi",
                attrs={
                    "hub_name": "pypi",
                    "python_version": _PYTHON_VERSION,
                    "requirements_lock": f"//:{_REQUIREMENTS_LOCK}",
                },
            )
            for coordinate in sorted(unit.external_coordinates, key=lambda c: c.key)
            if coordinate.ecosystem is Ecosystem.PYPI
        ]

    def workspace_files(self, units: Sequence[BuildUnit]) -> list[SupportFile]:
        """`//:requirements.lock` — carried when the repo ships one, DERIVED otherwise (D10).

        **Fleet-wide over every Python unit, not per repo**, for the reason `resolution()` gives:
        `pip.parse(requirements_lock = "//:requirements.lock")` names ONE file at the monorepo
        root, so a per-unit view offers N candidate files for one path and the driver's union keeps
        whichever it saw first. Exactly ONE `SupportFile` is returned however many units are
        handed in, and both of its fields are computed from the whole set — order-independent
        (§11.6), because the contributors are put in a total order first.

        Python is the ecosystem where deriving is legitimate: Phase 1 already recorded every
        declared dependency and its version spec on the unit's `external_coordinates`, and a
        requirements file is exactly that list written out. So a repo with no lock still gets a
        hub containing the distributions it actually declared, rather than a `pip.parse` pointed
        at a file that does not exist.

        A real `requirements.lock`/`requirements.txt` still wins (`carry_from`) **while exactly
        one unit contributes**: a resolution the repo tested against is a fact, one this adapter
        reconstructed from specs is an inference, and only one of them pins transitive
        dependencies at all. With one contributor the union IS that repo's dependency set, so its
        own lock is a resolution of it and re-resolving would silently move versions it tested.

        **With ≥2 contributors the `carry_from` is DROPPED**, and that is the Python half of
        ADR-0048's reasoning. `//:requirements.lock` is ONE file feeding ONE `@pypi` hub, so under
        two contributors the file the monorepo needs is a resolution of the UNION — which no
        single repo's lock is. Promoting one repo's lock to the root therefore describes a fleet
        that does not exist, and — because `cli._carried` skips the resolver entirely — does it
        without any resolver ever running: the other repo's distributions are simply absent from
        the hub its own `@pypi//<pkg>` labels resolve in, with nothing raised anywhere. It was
        worse than a coin toss: the carried candidate was the lexicographically first `dest`, so
        which repo's pins won was an artifact of string ordering. This is `models/build.py`'s
        `carry_from` → `Resolution` → `content` precedence selecting its MIDDLE term, exactly the
        case that precedence exists for; no repo's own lock is lost, Phase 2 left each at
        `<dest>/requirements.lock`. Two repos that pinned genuinely incompatible ranges then get
        a loud `uv` failure naming both specs (`resolution()` passes the specs through unmerged),
        which is the honest outcome for a conflict the monorepo cannot represent.

        Python cannot be made pin-preserving here the way the JS lock can, and that is structural
        rather than a choice: a pip requirements file is a flat set with one `==` per
        distribution and `pip.parse` reads one of them, so there is no per-importer construction
        to mirror pnpm's workspace with. The union resolve is what the single hub can honestly be.

        **`content` is now the floor below the floor.** `resolution()` declares a real resolver for
        exactly this file, so a repo that ships nothing gets a computed transitive closure and this
        text is reached only where no resolver is declared at all. It stays because the difference
        between the two is the whole point: the derived text says `requests>=2.31` and a resolution
        says `requests==2.34.2` **and** the four distributions `requests` itself needs — which is
        precisely what `pip.parse` asks its hub for and what the derived file could never supply.
        It is rendered over the union for the same reason the resolve is: a floor holding one
        unit's specs is the same silent drop one step further down.
        """
        contributors = sorted(
            (
                unit
                for unit in units
                if any(c.ecosystem is Ecosystem.PYPI for c in unit.external_coordinates)
            ),
            key=lambda u: (u.dest, str(u.unit_id)),
        )
        if not contributors:
            return []
        dest = contributors[0].dest.strip("/")
        return [
            SupportFile(
                path=_REQUIREMENTS_LOCK,
                carry_from=(
                    [f"{dest}/{name}" for name in _CARRIED_REQUIREMENTS]
                    if len(contributors) == 1
                    else []
                ),
                content=_requirements_text(
                    [
                        c
                        for unit in contributors
                        for c in unit.external_coordinates
                        if c.ecosystem is Ecosystem.PYPI
                    ]
                ),
            )
        ]

    def resolution(self, units: Sequence[BuildUnit]) -> Resolution | None:
        """`uv pip compile` over the declared specs → the transitive closure `pip.parse` needs.

        The input is the same text `workspace_files()` offers as its floor, which is the honest
        statement of what this harness knows: Phase 1 recorded the *specs*, and a resolver is what
        turns specs into a resolution. The output is a pip requirements file with an `==` pin and a
        `# via` provenance line per distribution — including the ones no manifest in the fleet
        names, which is the half `pip.parse` was failing on.

        **One resolve over every Python unit**, because `pip.parse(requirements_lock =
        "//:requirements.lock")` names ONE file at the monorepo root: a per-repo resolve produces
        one candidate lock per repo for that single path, the driver keeps the first, and every
        other repo's distributions are absent from the hub they resolve `@pypi//<pkg>` in. It is
        also the only place the fleet's Python versions are reconciled at all — `uv` sees the
        union of the specs and either finds one closure that satisfies them or fails loudly, which
        is the honest outcome for two repos that pinned incompatible ranges.

        Gated on `external_coordinates` exactly as `workspace_files()` is, now over ANY unit: with
        no external deps anywhere there is no lockfile to produce, and running a resolver over an
        empty input would write an empty file that is indistinguishable from a failed one. A unit
        that declares none simply contributes no lines.
        """
        coordinates = [
            c
            for unit in units
            for c in unit.external_coordinates
            if c.ecosystem is Ecosystem.PYPI
        ]
        if not coordinates:
            return None
        return Resolution(
            lock_path=_REQUIREMENTS_LOCK,
            argv=list(_RESOLVER),
            # `_requirements_text` sorts and dedupes its own input, so the union is independent of
            # the order the driver grouped the units in (§11.6).
            inputs=[SupportFile(path=_REQUIREMENTS_IN, content=_requirements_text(coordinates))],
        )

    def generate_targets(self, unit: BuildUnit) -> list[BuildTarget]:
        """One `py_library` over the package, plus a `py_binary` iff it has an entry module.

        `imports = ["."]` puts the unit's own directory on the target's `PYTHONPATH`, which is
        what makes `import acme.widget` resolve the same way it did in the source repo. Without
        it every intra-package import in a relocated tree breaks at once, and the failure looks
        like a bad rewrite rather than a missing attribute.
        """
        name = target_name(unit)
        deps = self.dep_labels(unit)
        srcs = self.sources(unit)
        attrs: dict[str, str | int | bool | list[str]] = {"imports": ["."]}
        data = self.non_source_files(unit)
        if data:
            attrs["data"] = data
        targets = [
            BuildTarget(
                package=unit.dest,
                name=name,
                rule="py_library",
                load_from="@rules_python//python:defs.bzl",
                srcs=srcs,
                deps=deps,
                attrs=attrs,
            )
        ]
        entry = select_entrypoint(srcs, self.entrypoints)
        if entry is not None:
            targets.append(
                BuildTarget(
                    package=unit.dest,
                    name=f"{name}_bin",
                    rule="py_binary",
                    load_from="@rules_python//python:defs.bzl",
                    srcs=[entry],
                    deps=[f":{name}"],
                    attrs={"main": entry, "imports": ["."]},
                )
            )
        return targets

    def test_targets(self, unit: BuildUnit) -> list[BuildTarget]:
        """One `py_test` over `tests/**`, depending on the library.

        One target rather than one per file: `pytest` collects the package as a whole (conftest,
        fixtures, plugins), and per-file targets would each re-import the package under a
        different rootdir — which is how a suite that passes under `pytest` starts failing under
        Bazel for reasons that have nothing to do with the migration.
        """
        test_srcs = self.test_sources(unit)
        if not test_srcs:
            return []
        name = target_name(unit)
        return [
            BuildTarget(
                package=unit.dest,
                name=f"{name}_test",
                rule="py_test",
                load_from="@rules_python//python:defs.bzl",
                srcs=test_srcs,
                deps=[f":{name}", *self.external_labels(unit)],
                attrs={"main": test_srcs[0], "imports": ["."]},
                testonly=True,
                visibility=["//visibility:private"],
            )
        ]

    def toolchain_requirements(self) -> list[ToolchainRequirement]:
        """A pinned hermetic interpreter. `rules_python` will otherwise use whatever `python3`
        the host has, which is the definition of a non-hermetic build and the reason a green
        wave on CI is red on a developer's laptop."""
        return [
            ToolchainRequirement(
                ruleset="rules_python",
                extension="python.toolchain",
                name=f"python_{_PYTHON_VERSION.replace('.', '_')}",
                version=_PYTHON_VERSION,
                attrs={"python_version": _PYTHON_VERSION},
            )
        ]

    def native_baseline(self, unit: BuildUnit) -> NativeBaseline:
        """Native (pre-migration) probe for a PyPI distribution: `pip install -e .` (the repo's
        own dependencies, resolved against its own `pyproject.toml`/`setup.py`, exactly as it
        would be before this harness ever touched it) then `pytest`, both run with the repo's own
        (PRE-migration) root as cwd — never `unit.dest`, which is where `layout()` (§3.3) decides
        the code lands AFTER migration and does not exist yet when a baseline runs (§3.1 step 1,
        before Phase 2).

        `test_unit_count` is derived from `test_targets(unit)` — 0 or 1, matching this adapter's
        own one-`py_test`-per-unit collapsing (ADR-0135 ruling 1; see `NativeBaseline`'s
        docstring). It is never `None`: every `PYPI` unit has SOME native baseline, even a trivial
        one with zero tests (`tests_lost`, `workers/buildverify.py:686`, expects exactly `0`, not
        a sentinel, for that case).

        **STATIC, not yet measured** — see `NativeBaseline.test_unit_count`'s own `Field` for the
        caveat: this reuses the MIGRATED side's own collapsing, so it cannot express a native
        suite that actually shrank, and Leg B/C must not wire it unchanged into
        `repos.baseline_test_count`.
        """
        return NativeBaseline(
            build_argv=["python3", "-m", "pip", "install", "-e", "."],
            test_argv=["python3", "-m", "pytest"],
            test_unit_count=native_test_unit_count(self.test_targets(unit)),
        )


def _requirements_text(coordinates: Sequence[Coordinate]) -> str:
    """The declared dependencies as a pip requirements file — one line per distribution.

    Sorted and deduplicated, because `SupportFile.content` is written into the monorepo by every
    repo of the wave and §11.6 requires the same plan to render the same bytes in every process.
    The header is what tells a reader (and the next run) that this file is DERIVED and not the
    repo's own resolution.

    A **set of full spec strings**, never a `{name: spec}` map, and that is Rule 11 in a data
    structure: two repos pinning `urllib3<2` and `urllib3>=2.2` both keep their line, so `uv`
    reports the conflict as `No solution found … unsatisfiable`. A name-keyed map would overwrite
    in place and emit whichever the iteration reached last, leaving one repo building against a
    version it explicitly excluded.
    """
    lines = sorted(
        {
            f"{c.name}{c.version_spec}" if c.version_spec else c.name
            for c in coordinates
            if c.name
        }
    )
    return "\n".join(
        [
            "# GENERATED BY fleet from the dependencies Phase 1 recorded — do not edit.",
            "# One Python repo that ships its own requirements.lock/requirements.txt has it",
            "# carried over instead; with two or more, the root lock is a resolution of THIS",
            "# union, because no single repo's lock is one.",
            *lines,
        ]
    ) + "\n"
