"""Rust: `CARGO` → `rust/`, via `rules_rust` / `crate.from_cargo` (§3.3, §7.5)."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import ClassVar, Final

from fleet.ecosystems.base import (
    EcosystemAdapter,
    path_segment,
    register,
    select_entrypoint,
    target_name,
    union_workspace_files,
)
from fleet.models.build import (
    BuildTarget,
    BuildUnit,
    SupportFile,
    ToolchainRequirement,
    WorkspaceDep,
)
from fleet.models.enums import ContractKind, Ecosystem
from fleet.models.repo import Coordinate

_EDITION: Final = "2021"
_RUST_VERSION: Final = "1.81.0"
_LIB_ENTRY: Final = "src/lib.rs"

_CARGO_LOCK_FILE: Final = "Cargo.lock"
_CARGO_MANIFEST_FILE: Final = "Cargo.toml"
"""The two root files `crate.from_cargo` reads, as PATHS; the labels below are built from them so
the file this adapter creates and the file it names cannot drift apart (D10)."""

_EMPTY_CARGO_LOCK: Final = (
    "# GENERATED BY fleet — no Cargo.lock was found in the source repo.\nversion = 3\n"
)


@register
class RustAdapter(EcosystemAdapter):
    """`rust/<crate>`; `crate.from_cargo` for external deps."""

    name: ClassVar[str] = "rust"
    ecosystems: ClassVar[frozenset[Ecosystem]] = frozenset({Ecosystem.CARGO})
    monorepo_dir: ClassVar[str] = "rust"
    ruleset: ClassVar[str | None] = "rules_rust"
    extension: ClassVar[str | None] = "crate.from_cargo"
    extension_bzl: ClassVar[Mapping[str, str]] = {
        # `extension.bzl`, SINGULAR, and under `crate_universe/` — read off rules_rust 0.54.1.
        # The toolchain extension next to it is plural (`rust/extensions.bzl`), which is exactly
        # why these labels are recorded per extension instead of derived from the module name.
        "crate": "@rules_rust//crate_universe:extension.bzl",
        "rust": "@rules_rust//rust:extensions.bzl",
    }
    repo_name: ClassVar[str | None] = "crates"
    library_rule: ClassVar[str] = "rust_library"
    binary_rule: ClassVar[str | None] = "rust_binary"
    test_rule: ClassVar[str | None] = "rust_test"
    library_bzl: ClassVar[str | None] = "@rules_rust//rust:defs.bzl"
    binary_bzl: ClassVar[str | None] = "@rules_rust//rust:defs.bzl"
    test_bzl: ClassVar[str | None] = "@rules_rust//rust:defs.bzl"
    entrypoints: ClassVar[tuple[str, ...]] = ("main.rs",)
    src_suffixes: ClassVar[tuple[str, ...]] = (".rs",)
    """`rust_library.srcs` is Rust source only; a `Cargo.toml` belongs to `crate.from_cargo`'s
    manifest list, not to the target, and `compile_data`/`data` carry anything else."""
    contract_bindings: ClassVar[Mapping[ContractKind, str]] = {
        ContractKind.PROTO: "rust_proto_library",
        ContractKind.OPENAPI: "genrule",
        ContractKind.SHARED_LIB: "rust_library",
    }

    def path_tail(self, coordinate: Coordinate) -> str:
        """`<crate>` — crates.io is one flat namespace, so the crate name IS the address.

        The *directory* keeps the published spelling (`serde-json` stays hyphenated) while the
        `crate_name` attribute below is the underscored identifier `rustc` requires; conflating
        them would either give a directory nobody can find from `Cargo.toml` or a crate name that
        does not compile.
        """
        return path_segment(coordinate.name)

    def import_specifier(self, coordinate: Coordinate, dest: str) -> str:
        """The crate identifier a `use` statement names: the crate name, `-` folded to `_`.

        `serde-json` is published hyphenated and written `serde_json` in source, which is the
        same split `path_tail` documents from the other end — the directory keeps the published
        spelling and the identifier is what `rustc` accepts. Relocation changes neither: the
        `rust_library`'s `crate_name` travels with the target.
        """
        _ = dest
        return path_segment(coordinate.name).replace("-", "_").replace(".", "_")

    def workspace_deps(self, unit: BuildUnit) -> list[WorkspaceDep]:
        """`crate.from_cargo` over the workspace `Cargo.lock` — the lock is the resolution.

        Cargo's resolver has already unified feature flags across the whole workspace, and a
        per-crate re-declaration here would drop the unified feature set: the same dependency
        would then build with different features for two consumers and fail to link.
        """
        return [
            WorkspaceDep(
                ruleset="rules_rust",
                extension="crate.from_cargo",
                coordinate=coordinate,
                repo_name="crates",
                attrs={
                    "name": "crates",
                    "cargo_lockfile": f"//:{_CARGO_LOCK_FILE}",
                    "manifests": [f"//:{_CARGO_MANIFEST_FILE}"],
                },
            )
            for coordinate in sorted(unit.external_coordinates, key=lambda c: c.key)
            if coordinate.ecosystem in self.ecosystems
        ]

    def workspace_files(self, units: Sequence[BuildUnit]) -> list[SupportFile]:
        """`//:Cargo.lock` — carried — and `//:Cargo.toml`, a REAL workspace naming every
        contributing crate (D10).

        **Fleet-wide over every Rust unit, not per repo**: both files sit at the monorepo ROOT,
        one per path, so a per-unit view offers N candidates for each and the driver's union keeps
        whichever it saw first.

        **The manifest is computed from the whole unit set and its `carry_from` is dropped**, and
        those are one decision. `_workspace_manifest` was rendered per unit, naming that one unit
        in `members`, and `union_workspace_files`' first-writer-wins `setdefault` then discarded
        every later unit's copy — so a two-Rust-repo fleet got a workspace with one member and the
        second repo's crate was simply not in it, with nothing raised anywhere
        (`_fleet_support_files` hands every plan of an ecosystem the identical tuple, so
        `RootFileConflictError` structurally cannot fire on it). The carry was the same defect from
        the other end: a repo's
        own `Cargo.toml` is a `[package]` manifest with **no `[workspace]` table**, and
        crate_universe's `SplicerKind::new` dispatches on exactly that — handed one it takes the
        `Package` branch instead of the `Workspace` branch, so only that crate's dependencies ever
        reach the `@crates` hub. This is `js.py`'s argument for `pnpm-workspace.yaml` in Cargo's
        dialect: a *workspace* manifest describes a workspace no source repo has ever seen, so no
        source repo's copy of it can be promoted here. The repo's own manifest is not lost — Phase
        2 left it at `<dest>/Cargo.toml`, which `package_files()` declares as the member's own.

        **The lock keeps its `carry_from`, and that is NOT an oversight** — the Python rule
        (ADR-0049: drop the carry at ≥2 contributors) is deliberately not copied, because Cargo has
        the downstream resolver `pip.parse` lacks. `crate_universe`'s `LockGenerator::generate`
        runs `cargo fetch` **without** `--locked` when a lock is present, so cargo repairs and
        *extends* a partial lock: one repo's carried pins survive and the other repo's crates are
        added to them. The empty floor (`version = 3`, no `[[package]]`) would throw every pin
        away instead. Which is also the reason `workspace_deps` gives: Cargo's resolver has already
        unified feature flags, and a lock this harness wrote would drop that unification.

        **The extension is never committed, and that is deliberate.** `crate.from_cargo` rewrites
        `//:Cargo.lock` in the worktree as it runs (`skip_cargo_lockfile_overwrite` defaults
        False), and `cli.BuildPipelineWorker._publish` re-asserts the planned bytes over it before
        staging — otherwise the one repo whose build ran green would publish a lock no sibling
        could merge (§11.6). The cost is that every Phase 3 and Phase 4 build re-extends from the
        seeded lock instead of from the previous build's output. That is the same `cargo fetch`
        without `--locked` described above doing the same work again, and it throws nothing away:
        this harness declares no Cargo resolution, so the extension was never an artifact anyone
        was keeping.
        """
        contributors = sorted(
            (
                unit
                for unit in units
                if any(c.ecosystem in self.ecosystems for c in unit.external_coordinates)
            ),
            key=lambda u: (u.dest, str(u.unit_id)),
        )
        if not contributors:
            return []
        return [
            *union_workspace_files(contributors, self._unit_workspace_files),
            SupportFile(
                path=_CARGO_MANIFEST_FILE,
                content=_workspace_manifest(_member_dests(contributors)),
            ),
        ]

    def _unit_workspace_files(self, unit: BuildUnit) -> list[SupportFile]:
        """One unit's contribution to the root `Cargo.lock` — the one root file still per-unit.

        It stays per-unit because it is the one whose honest value IS one repo's file: the carry
        candidate has to live under a contributing unit's own `dest`, and the union's total order
        decides which repo's lock seeds the root (cargo extends it from there). The manifest above
        cannot be expressed this way at all, which is why it is no longer here.
        """
        if not any(c.ecosystem in self.ecosystems for c in unit.external_coordinates):
            return []
        dest = unit.dest.strip("/")
        return [
            SupportFile(
                path=_CARGO_LOCK_FILE,
                carry_from=[f"{dest}/{_CARGO_LOCK_FILE}"],
                content=_EMPTY_CARGO_LOCK,
            )
        ]

    def package_files(self, unit: BuildUnit) -> list[SupportFile]:
        """`<dest>/Cargo.toml` — the member manifest the root workspace's `members` entry NAMES.

        The other half of making the root a real workspace: `members = ["rust/acme-store"]` is a
        promise that `rust/acme-store/Cargo.toml` is loadable, and `cargo metadata` fails the whole
        workspace — not just that member — when it is not. So the silent drop this change closes
        would have been traded for a hard failure had the file been left to chance.

        Carried FROM ITSELF, exactly as `js.py`'s `tsconfig.json` is: relocation already put a
        repo's own `Cargo.toml` at this path, so naming the path as its own candidate makes
        materializing it a no-op rather than a clobber, and `content` is the floor for a repo that
        shipped none. Gated on the same `external_coordinates` the root workspace gates `members`
        on, so the set of member manifests and the set of members are the same set by construction:
        a floor written for a directory no `members` entry names is a file nothing reads.
        """
        if not any(c.ecosystem in self.ecosystems for c in unit.external_coordinates):
            return []
        path = f"{unit.dest.strip('/')}/{_CARGO_MANIFEST_FILE}"
        return [SupportFile(path=path, carry_from=[path], content=_member_manifest(unit))]

    def generate_targets(self, unit: BuildUnit) -> list[BuildTarget]:
        """A `rust_library` rooted at `src/lib.rs`, plus a `rust_binary` rooted at `src/main.rs`.

        `crate_root` is explicit rather than inferred: a crate with both files is the ordinary
        library-plus-CLI shape, and without the root attribute `rules_rust` picks one by
        convention and silently compiles the binary's `main` into the library.
        """
        name = target_name(unit)
        deps = self.dep_labels(unit)
        srcs = self.sources(unit)
        attrs: dict[str, str | int | bool | list[str]] = {
            "crate_name": _crate_name(unit),
            "edition": _EDITION,
        }
        data = self.non_source_files(unit)
        if data:
            attrs["compile_data"] = data
        if _LIB_ENTRY in srcs:
            attrs["crate_root"] = _LIB_ENTRY
        targets = [
            BuildTarget(
                package=unit.dest,
                name=name,
                rule="rust_library",
                load_from="@rules_rust//rust:defs.bzl",
                srcs=srcs,
                deps=deps,
                attrs=attrs,
                visibility=["//visibility:public"],
            )
        ]
        entry = select_entrypoint(srcs, self.entrypoints)
        if entry is not None:
            targets.append(
                BuildTarget(
                    package=unit.dest,
                    name=f"{name}_bin",
                    rule="rust_binary",
                    load_from="@rules_rust//rust:defs.bzl",
                    srcs=[entry],
                    deps=[f":{name}", *deps],
                    attrs={"crate_root": entry, "edition": _EDITION},
                    visibility=["//visibility:private"],
                )
            )
        return targets

    def test_targets(self, unit: BuildUnit) -> list[BuildTarget]:
        """One `rust_test` with `crate = ":<lib>"` for in-crate `#[cfg(test)]` unit tests, plus
        one SEPARATE `rust_test(srcs = [file], deps = [":<lib>", ...])` per Cargo integration-test
        file (D112, round VI task 86) — never combined on the same target.

        `crate =` rather than `srcs =` for the unit-test target because Rust unit tests live
        *inside* the crate behind `#[cfg(test)]`: compiling the test sources as a separate crate
        would leave every `#[cfg(test)] mod tests` in `src/` untested while reporting a green
        `bazel test`. And `crate=`/`srcs=` can never both be set on one target: `rules_rust`'s own
        `_rust_test_impl` (`rust/private/rust.bzl`, verified against the pinned
        `rules_rust@0.65.0` tag) hard-fails analysis the instant both are non-empty — `"rust_test.
        crate and rust_test.srcs are mutually exclusive"` — which is why `test_sources(unit)`
        (Cargo's own `tests/*.rs` convention, `cli._is_rust_test_src`) drives a SEPARATE target per
        file instead of widening this one's `srcs`. This is not a Bazel workaround; it is the same
        split Cargo itself already makes — each `tests/` file compiles as its own independently
        linked test binary, never folded into the library crate the way a `#[cfg(test)]` block is.
        """
        name = target_name(unit)
        deps = self.dep_labels(unit)
        test_srcs = self.test_sources(unit)
        targets: list[BuildTarget] = []
        if self.sources(unit):
            targets.append(
                BuildTarget(
                    package=unit.dest,
                    name=f"{name}_test",
                    rule="rust_test",
                    load_from="@rules_rust//rust:defs.bzl",
                    attrs={"crate": f":{name}", "edition": _EDITION},
                    testonly=True,
                    visibility=["//visibility:private"],
                )
            )
        for test_src in test_srcs:
            targets.append(
                BuildTarget(
                    package=unit.dest,
                    name=_integration_test_target_name(name, test_src),
                    rule="rust_test",
                    load_from="@rules_rust//rust:defs.bzl",
                    srcs=[test_src],
                    deps=[f":{name}", *deps],
                    attrs={"edition": _EDITION},
                    testonly=True,
                    visibility=["//visibility:private"],
                )
            )
        return targets

    def toolchain_requirements(self) -> list[ToolchainRequirement]:
        """A pinned `rustc`. Rust's edition and toolchain move fast enough that "whatever is on
        the host" is a different compiler between two waves of the same run.

        **The pin goes in `attrs`, spelled `versions`, or it does not reach `MODULE.bazel`.**
        `_tag_attrs` renders an adapter's `attrs` verbatim and falls back to `name`/`version` only
        when the adapter declared none; this adapter declared `{"edition": …}`, so the fallback
        never fired and the emitted tag was `rust.toolchain(edition = "2021")` — the constant
        below reached nothing and the fleet built against whatever `rules_rust` defaults to. The
        fallback firing would not have helped either: `rules_rust`'s `rust.toolchain` tag class
        has no `name` and no `version` attribute at all (read off `rust/extensions.bzl`), so both
        would have been rejected by Bazel's loader. `versions` is a `string_list`, hence the
        one-element list, and `_render_attr` already renders a list.

        **Never `[]`.** `_rust_impl` reads `root.tags.toolchain or rules_rust.tags.toolchain`, so
        this tag REPLACES the ruleset's default rather than adding to it, and it special-cases an
        empty `versions` into `_empty_repository(name = "rust_toolchains")` — a `@rust_toolchains`
        that registers no toolchain whatsoever.
        """
        return [
            ToolchainRequirement(
                ruleset="rules_rust",
                extension="rust.toolchain",
                name="rust_toolchains",
                version=_RUST_VERSION,
                attrs={"edition": _EDITION, "versions": [_RUST_VERSION]},
            )
        ]


def _member_dests(units: Sequence[BuildUnit]) -> list[str]:
    """Every contributing unit's monorepo path, deduped and sorted — the workspace's `members`.

    Sorted rather than left in the caller's order, and deduped rather than trusted to be unique,
    because this list is the bytes of a file committed onto the integration branch: the driver
    groups the units and nothing orders them, so two runs of the same fleet must not render two
    different manifests (§11.6).
    """
    return sorted({unit.dest.strip("/") for unit in units})


def _workspace_manifest(members: Sequence[str]) -> str:
    """A minimal Cargo workspace manifest naming EVERY contributing crate as a member.

    The floor, not a resolution: it declares the members and the resolver version so
    `crate.from_cargo` has a workspace to splice, and nothing about dependency versions — which is
    the `Cargo.lock`'s job and the reason that file is carried rather than synthesized.

    Every member, because this is ONE file at the monorepo root describing the whole fleet's Rust:
    a manifest naming one of two crates is a workspace the second crate is not in, and cargo's
    answer is to resolve the first one's dependencies and nothing else.
    """
    listed = ", ".join(f'"{dest}"' for dest in members)
    return (
        "# GENERATED BY fleet — the monorepo's Cargo workspace: one member per Rust crate.\n"
        "[workspace]\n"
        'resolver = "2"\n'
        f"members = [{listed}]\n"
    )


def _member_manifest(unit: BuildUnit) -> str:
    """The floor `[package]` manifest for a workspace member that shipped no `Cargo.toml`.

    A `[package]` and not a `[workspace]`: this is a *member*, and a member directory holding a
    second workspace table is what cargo rejects as a nested workspace. It names no dependencies
    for the same reason the root names no versions — the `Cargo.lock` is the resolution.

    The package name is the `rustc` identifier `generate_targets()` puts on the crate's
    `crate_name`, so the manifest and the Bazel target agree on what this crate is called.
    """
    return (
        "# GENERATED BY fleet — no Cargo.toml was found in the source repo.\n"
        "[package]\n"
        f'name = "{_crate_name(unit)}"\n'
        'version = "0.0.0"\n'
        f'edition = "{_EDITION}"\n'
    )


def _integration_test_target_name(base: str, test_src: str) -> str:
    """`<crate>_<file>_test` — one Bazel target name per Cargo integration-test file.

    Sanitized the same way `_crate_name` sanitizes a published name (non-alphanumeric → `_`):
    a `rust_test` target name is a Bazel label component, not a filesystem path, and `test_src`
    here is always `tests/<file>.rs` (`cli._is_rust_test_src`), so only the file's own stem needs
    sanitizing — the `tests/` prefix and `.rs` suffix carry no information once split into their
    own target.
    """
    stem = test_src.rsplit("/", maxsplit=1)[-1]
    if stem.endswith(".rs"):
        stem = stem[: -len(".rs")]
    ident = "".join(ch if ch.isalnum() else "_" for ch in stem)
    return f"{base}_{ident}_test"


def _crate_name(unit: BuildUnit) -> str:
    """The `rustc` crate identifier: lowercased, `-`/`.` → `_`, never leading with a digit."""
    source = unit.published.name if unit.published is not None else target_name(unit)
    ident = "".join(ch if ch.isalnum() else "_" for ch in source.strip().lower())
    if not ident:
        return "crate"
    return f"_{ident}" if ident[0].isdigit() else ident
