"""`BUILD.bazel` and `MODULE.bazel` text generation, and MVS version reconciliation (§3.3).

Pure: data in, text out. Nothing here shells out, reads a file, or needs `bazel` on `PATH` —
which is what lets Phase 3's whole emission layer be tested offline, and what makes the
"generated BUILD files are byte-identical across processes" property (§11.6) checkable rather
than aspirational. Every ordering below is an explicit `sorted(...)`; not one of them is "the
order the dict happened to be in", because a `dict` populated from a `set` re-orders under a
different `PYTHONHASHSEED` and would rewrite the whole monorepo on the next run.

**Version reconciliation is real MVS, not a vote.** Each requirement is recorded as a
`bazel_dep`, and the selected version is the **minimum version satisfying ALL specs** — exactly
what Bazel's Minimal Version Selection computes as the maximum of the declared lower bounds,
checked against every declared upper bound. The rule this replaces was "the highest version
satisfying the most specs", which is a plurality vote wearing MVS's name: with 30 repos pinned
`[31, 32)` and 31 repos pinned `[33, 34)` it selects 33 and ships a build that violates 30
repos' declared upper bound, silently. Here that spec set has an **empty intersection**, so it
raises `VersionConflict` at `severity='error'` and *only then* is the `conflict_resolution` role
(§7.7) allowed an opinion — whose proposal `validate_override` re-derives against every
contributing spec before a line of it is written. The model may choose which promise to break;
it may not tell us which promises it kept.
"""

from __future__ import annotations

import json
import re
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass, field
from typing import Final, Literal, Protocol, runtime_checkable

from fleet.graph.collisions import VersionRequirement
from fleet.graph.cycles import CoarsePlan, GraphFinding
from fleet.models.build import BuildTarget, GazelleConfig, ToolchainRequirement, WorkspaceDep
from fleet.models.enums import Ecosystem

__all__ = [
    "GENERATED_HEADER",
    "OVERRIDE_MECHANISMS",
    "OverrideDecision",
    "OverrideProposal",
    "VersionConflict",
    "VersionRange",
    "VersionResolution",
    "coarse_build_targets",
    "mvs_select",
    "parse_range",
    "reconcile_versions",
    "render_build_bazel",
    "render_gazelle_build",
    "render_module_bazel",
    "render_root_package",
    "render_target",
    "resolve_workspace_deps",
    "stub_failing_target",
    "validate_override",
]

GENERATED_HEADER: Final = (
    "# GENERATED BY fleet — do not edit (SPEC §3.3 step 2).\n"
    "# BUILD.bazel files are always generated, never hand-edited: an edit here is lost on the\n"
    "# next regeneration and the loss is silent.\n"
)

OVERRIDE_MECHANISMS: Final[frozenset[str]] = frozenset({"bazel_dep", "single_version_override"})
"""The only two MODULE.bazel constructs this module knows how to emit — the same closed set
`VersionConflictResolution.mechanism` is patterned on (§7.7)."""

_INDENT: Final = "    "


# =======================================================================================
# Starlark value rendering
# =======================================================================================


def _render_scalar(value: str | int | bool) -> str:
    """Starlark's scalar syntax is JSON's for exactly these three types, and `json.dumps` is the
    escaper we do not have to get right ourselves for a path containing a quote."""
    if isinstance(value, bool):  # before int: bool IS an int in Python, and `True` != `1` here
        return "True" if value else "False"
    if isinstance(value, int):
        return str(value)
    return json.dumps(value)


def _render_attr(name: str, value: str | int | bool | Sequence[str]) -> list[str]:
    if isinstance(value, str | int | bool):
        return [f"{_INDENT}{name} = {_render_scalar(value)},"]
    lines = [f"{_INDENT}{name} = ["]
    lines += [f"{_INDENT * 2}{_render_scalar(item)}," for item in value]
    lines.append(f"{_INDENT}],")
    return lines


def render_target(target: BuildTarget) -> str:
    """One rule instance, in a fixed attribute order.

    Empty lists are omitted rather than rendered as `[]`: an adapter that returns no `deps` and
    an adapter that returns `deps = []` must produce the same bytes, or a no-op adapter change
    shows up as a diff on 250 BUILD files.
    """
    lines = [f"{target.rule}("]
    lines += _render_attr("name", target.name)
    if target.srcs:
        lines += _render_attr("srcs", target.srcs)
    if target.deps:
        lines += _render_attr("deps", sorted(set(target.deps)))
    for key in sorted(target.attrs):
        lines += _render_attr(key, target.attrs[key])
    if target.testonly:
        lines += _render_attr("testonly", True)
    if target.visibility:
        lines += _render_attr("visibility", target.visibility)
    lines.append(")")
    return "\n".join(lines)


def _load_statements(targets: Iterable[BuildTarget]) -> list[str]:
    by_bzl: dict[str, set[str]] = {}
    for target in targets:
        if target.load_from is not None:
            by_bzl.setdefault(target.load_from, set()).add(target.rule)
    return [
        "load("
        + ", ".join([_render_scalar(bzl)] + [_render_scalar(s) for s in sorted(by_bzl[bzl])])
        + ")"
        for bzl in sorted(by_bzl)
    ]


def render_build_bazel(targets: Sequence[BuildTarget], *, header: str = GENERATED_HEADER) -> str:
    """A whole `BUILD.bazel`, deterministic and byte-stable for a given target list.

    Targets are sorted by `(name, rule)` and loads by `.bzl` label, so two runs over the same
    plan — in different processes, under different hash seeds — produce identical bytes and the
    integration branch shows a diff only where the *inputs* changed.
    """
    packages = {t.package for t in targets}
    if len(packages) > 1:
        raise ValueError(
            f"render_build_bazel got targets from {len(packages)} packages "
            f"({', '.join(sorted(packages))}); one BUILD file describes exactly one package"
        )
    ordered = sorted(targets, key=lambda t: (t.name, t.rule))
    blocks = _load_statements(ordered)
    body = [render_target(t) for t in ordered]
    chunks = [header.rstrip("\n")]
    if blocks:
        chunks.append("\n".join(blocks))
    chunks.extend(body)
    return "\n\n".join(chunks) + "\n"


def render_root_package(
    paths: Sequence[str],
    *,
    targets: Sequence[BuildTarget] = (),
    header: str = GENERATED_HEADER,
) -> str:
    """The monorepo root's `BUILD.bazel`, exporting every root file a MODULE.bazel tag NAMES.

    **`//:requirements.lock` is a LABEL, and a label needs a package.** Materialising the file
    (D10) was only half the contract: with no `BUILD.bazel` at the monorepo root the root is not
    a Bazel package at all, and real Bazel answers `Error in read: Unable to load package for
    //:requirements.lock: BUILD file not found in any of the following directories`, from inside
    `rules_python`'s `parse_requirements.bzl`, for a file that is sitting right there on disk.
    The same sentence is owed to `npm_translate_lock`'s `//:pnpm-lock.yaml` and
    `//:.bazelignore`, and to `crate.from_cargo`'s `//:Cargo.lock`.

    Exported explicitly rather than by `glob(["*"])`: the export list is then exactly the set of
    files some adapter declared, so a root file that stops being declared stops being exported
    and the monorepo root never accumulates a public surface nobody asked for.

    `targets` are the RULES an adapter needs in this package — `root_targets()`, which today is
    rules_js's `npm_link_all_packages()` and the only reason the pnpm virtual store that every
    `node_modules/<pkg>` link resolves through exists at all.
    Taken as data, so this module still knows no language: it renders whatever loads and rules it
    is handed, sorted, and a target whose `package` is not the root is a caller error rather than
    a file that quietly declares a rule in the wrong place.
    """
    misplaced = sorted({t.package for t in targets if t.package.strip("/")})
    if misplaced:
        raise ValueError(
            f"render_root_package got targets from {misplaced}; the root package is '' and a "
            f"target declared here would be addressed as //:<name> whatever its package says"
        )
    ordered = sorted(targets, key=lambda t: (t.name, t.rule))
    exported = "".join(f"{_INDENT}{_INDENT}{json.dumps(path)},\n" for path in sorted(set(paths)))
    chunks = [header.rstrip("\n")]
    loads = _load_statements(ordered)
    if loads:
        chunks.append("\n".join(loads))
    chunks.extend(render_target(target) for target in ordered)
    chunks.append(
        "exports_files(\n"
        f"{_INDENT}[\n{exported}{_INDENT}],\n"
        f'{_INDENT}visibility = ["//visibility:public"],\n'
        ")"
    )
    return "\n\n".join(chunks) + "\n"


def render_gazelle_build(config: GazelleConfig, *, header: str = GENERATED_HEADER) -> str:
    """The `# gazelle:` directive preamble written *before* the generator runs (§3.3 step 2).

    Emitted instead of targets — a `uses_gazelle` adapter delegates emission and does not
    pretend to generate targets itself, so this file deliberately declares none.
    """
    lines = [header.rstrip("\n"), ""]
    if config.prefix is not None:
        lines.append(f"# gazelle:prefix {config.prefix}")
    lines += [f"# gazelle:exclude {path}" for path in config.exclude]
    lines += list(config.directives)
    return "\n".join(lines) + "\n"


def coarse_build_targets(
    plan: CoarsePlan,
    rules: Mapping[Ecosystem, str],
    *,
    load_from: Mapping[Ecosystem, str] | None = None,
) -> list[BuildTarget]:
    """§3.1 6e → `BuildTarget`s: **one** library target per `(ecosystem, scc_id)`.

    The union of the members' sources, in one target, is the whole point: 6e is reached because
    the members are mutually dependent, so one target per member reproduces the SCC in the Bazel
    target graph and every repo in the SCC's dependent cone is stranded behind a build that can
    never go green. `CoarseTarget.name` already folds `scc:` to `scc_` — a `:` inside a target
    name does not parse as a label at all.

    `rules` maps an ecosystem to its library rule name. It is a parameter because the rule name
    is adapter knowledge (§7.5) and `bazel/` carries no ecosystem exemption (§13 row 6); the
    driver reads it off the registry and hands it in.
    """
    loads = load_from or {}
    out: list[BuildTarget] = []
    for coarse in sorted(plan.targets, key=lambda t: (t.ecosystem.value, t.scc_id)):
        rule = rules.get(coarse.ecosystem)
        if rule is None:
            raise ValueError(
                f"{coarse.scc_id}: no library rule registered for {coarse.ecosystem.value}; "
                "an ATOMIC_WAVE SCC cannot be coarsened without one (Rule 11: fail loud)"
            )
        out.append(
            BuildTarget(
                package=coarse.package,
                name=coarse.name,
                rule=rule,
                load_from=loads.get(coarse.ecosystem),
                srcs=list(coarse.srcs),
                attrs={"tags": [f"fleet_scc={coarse.scc_id}"]},
            )
        )
    return out


_STUB_FAILING_TARGET_NAME: Final = "stub"
"""The single target `bazel.layout.stub_dest(coord_key)` names — `//<stub_dest>:stub`."""

_STUB_FAILING_OUT: Final = "UNBUILDABLE"
"""Never produced: `cmd` exits before writing it. A real output name is still required —
`genrule` refuses an empty `outs` — and this one names the reason in the label itself."""


def stub_failing_target(*, coord_key: str, provider_repo_id: str, dest: str) -> BuildTarget:
    """§3.5 item 2 — the never-published half of the stub-creation bundle (task-68, Leg 2).

    A single, GENERIC (non-per-ecosystem) `genrule`: it is a Bazel-native rule needing no
    `load()`, so it renders identically whether the abandoned provider was Maven, npm, PyPI,
    crates.io or a Go module — no adapter branch is needed, and §12.6's confinement rule (no raw
    `Ecosystem` check outside `manifests/`/`ecosystems/`/`config/rules/`) would forbid one here
    anyway. This is the shape research-7 §5 flagged as likely and CLAUDE.md's own directive is to
    try the ecosystem-agnostic form first — this one needed no adapter branch to satisfy it.

    `cmd` runs `exit 1` after an `echo` to stderr naming the abandoned provider and its
    coordinate, so the failure is a genuine BUILD-time action failure (SPEC §3.5 item 2: "fails
    at build time with an explicit message, never at runtime silently") — never a green build
    that quietly ships an empty package nothing consumes. `outs` names one file that is never
    produced: `cmd` exits before Bazel ever checks for it, so the actual failure is always the
    exit code and the message, not a missing-output error that would obscure it.
    """
    message = (
        f"fleet: {provider_repo_id} (coordinate {coord_key}) is REQUIRES_HUMAN_INTERVENTION "
        "with no published artifact; this EMPTY_FAILING stub cannot be built. Resolve the "
        "abandoned repo or replace this dependency (SPEC section 3.5 item 2)."
    )
    return BuildTarget(
        package=dest,
        name=_STUB_FAILING_TARGET_NAME,
        rule="genrule",
        attrs={
            "outs": [_STUB_FAILING_OUT],
            "cmd": f"echo {json.dumps(message)} >&2; exit 1",
        },
    )


# =======================================================================================
# Versions — parsing, MVS selection, conflict detection
# =======================================================================================

_ATOM = re.compile(r"^(==|>=|<=|=|>|<|\^|~>|~)?\s*v?(\d+(?:\.\d+)*)")
"""The same spec grammar `graph/collisions.py` audits with. That module answers the weaker
question — *is the intersection non-empty* — at Phase 1; Phase 3 needs the **selected version**,
which no satisfiability predicate returns. See HONEST_GAPS: a shared `util/semver.py` is the
right home for both, and creating it is outside this change's blast radius."""


def _pad(version: tuple[int, ...], width: int) -> tuple[int, ...]:
    return version + (0,) * (width - len(version))


def _cmp(a: tuple[int, ...], b: tuple[int, ...]) -> int:
    width = max(len(a), len(b))
    left, right = _pad(a, width), _pad(b, width)
    return (left > right) - (left < right)


def _parse_version(text: str) -> tuple[int, ...]:
    return tuple(int(part) for part in text.split("."))


@dataclass(frozen=True, slots=True)
class VersionRange:
    """One requirement as a half-open interval, keeping the version *text* as written.

    The text matters: `bazel_dep(version = ...)` is compared by Bazel's own version parser, and
    rewriting a declared `31` as `31.0.0` is a change to the module graph we did not intend.
    """

    lower: tuple[int, ...] | None = None
    lower_text: str = ""
    lower_inclusive: bool = True
    upper: tuple[int, ...] | None = None
    upper_inclusive: bool = False

    @property
    def is_empty(self) -> bool:
        if self.lower is None or self.upper is None:
            return False
        order = _cmp(self.lower, self.upper)
        if order > 0:
            return True
        return order == 0 and not (self.lower_inclusive and self.upper_inclusive)

    def contains(self, version: tuple[int, ...]) -> bool:
        if self.lower is not None:
            order = _cmp(version, self.lower)
            if order < 0 or (order == 0 and not self.lower_inclusive):
                return False
        if self.upper is not None:
            order = _cmp(version, self.upper)
            if order > 0 or (order == 0 and not self.upper_inclusive):
                return False
        return True

    def intersect(self, other: VersionRange) -> VersionRange:
        lower, lower_text, lower_inclusive = self.lower, self.lower_text, self.lower_inclusive
        if other.lower is not None and (
            lower is None
            or _cmp(other.lower, lower) > 0
            or (_cmp(other.lower, lower) == 0 and not other.lower_inclusive)
        ):
            lower, lower_text, lower_inclusive = (
                other.lower,
                other.lower_text,
                other.lower_inclusive,
            )
        upper, upper_inclusive = self.upper, self.upper_inclusive
        if other.upper is not None and (
            upper is None
            or _cmp(other.upper, upper) < 0
            or (_cmp(other.upper, upper) == 0 and not other.upper_inclusive)
        ):
            upper, upper_inclusive = other.upper, other.upper_inclusive
        return VersionRange(
            lower=lower,
            lower_text=lower_text,
            lower_inclusive=lower_inclusive,
            upper=upper,
            upper_inclusive=upper_inclusive,
        )


def _caret_ceiling(version: tuple[int, ...]) -> tuple[int, ...]:
    major, minor, patch = _pad(version, 3)[:3]
    if major:
        return (major + 1, 0, 0)
    if minor:
        return (0, minor + 1, 0)
    return (0, 0, patch + 1)


def parse_range(spec: str) -> VersionRange | None:
    """One version spec → a `VersionRange`, or `None` when the grammar does not cover it.

    `None` is not "unconstrained": an unparseable spec is *excluded* from the intersection and
    reported, because a `VersionConflict` at `severity='error'` blocks the run and must never
    rest on a parse this module was not sure of.
    """
    atoms = [a.strip() for a in re.split(r"[,\s]+", spec.strip()) if a.strip()]
    if not atoms:
        return None
    out = VersionRange()
    for atom in atoms:
        match = _ATOM.match(atom)
        if match is None:
            return None
        op = match.group(1) or "=="
        text = match.group(2)
        version = _parse_version(text)
        if op in ("==", "="):
            one = VersionRange(version, text, True, version, True)
        elif op == ">=":
            one = VersionRange(version, text, True)
        elif op == ">":
            one = VersionRange(version, text, False)
        elif op == "<=":
            one = VersionRange(upper=version, upper_inclusive=True)
        elif op == "<":
            one = VersionRange(upper=version)
        elif op == "^":
            one = VersionRange(version, text, True, _caret_ceiling(version), False)
        else:  # `~` / `~>`: pin the minor
            major, minor = _pad(version, 2)[:2]
            one = VersionRange(version, text, True, (major, minor + 1, 0), False)
        out = out.intersect(one)
    return out


class VersionConflict(Exception):
    """An external coordinate whose specs have an **empty intersection** (§13 row 17).

    Always `severity='error'`: there is no version that honours every declared bound, so any pin
    breaks a promise some repo made, and choosing which promise to break is not a decision this
    module is entitled to make silently. This is the one — and only — gate to the
    `conflict_resolution` LLM role.
    """

    severity: Final[Literal["error"]] = "error"

    def __init__(
        self, coord_key: str, specs: Sequence[str], repo_ids: Sequence[str], reason: str
    ) -> None:
        self.coord_key = coord_key
        self.specs = tuple(specs)
        self.repo_ids = tuple(repo_ids)
        self.reason = reason
        super().__init__(
            f"{coord_key}: {reason}; specs={list(self.specs)} from repos={list(self.repo_ids)}"
        )

    def as_finding(self) -> GraphFinding:
        """The `findings` row (§6, kind `VersionConflict`) this conflict is recorded as."""
        return GraphFinding(
            kind="VersionConflict",
            severity="error",
            payload={
                "coord_key": self.coord_key,
                "specs": ", ".join(self.specs),
                "repo_ids": ", ".join(self.repo_ids),
                "reason": self.reason,
            },
        )


def _grouped(requirements: Iterable[VersionRequirement]) -> dict[str, list[VersionRequirement]]:
    out: dict[str, list[VersionRequirement]] = {}
    for req in sorted(requirements, key=lambda r: (r.coord_key, r.repo_id, r.version_spec)):
        out.setdefault(req.coord_key, []).append(req)
    return out


def mvs_select(coord_key: str, requirements: Sequence[VersionRequirement]) -> str:
    """The **minimum version satisfying every spec** — Bazel's MVS, over one coordinate.

    MVS is the maximum of the declared lower bounds, which is the smallest version that can
    satisfy them all; it is then checked against every declared upper bound. A version that
    satisfies *most* specs is never selected, however large that majority: 30 repos pinned
    `[31, 32)` do not lose a vote to 31 repos pinned `[33, 34)`, they produce a conflict.
    """
    reqs = [r for r in requirements if r.coord_key == coord_key]
    if not reqs:
        raise ValueError(f"{coord_key}: no requirements to select from")
    specs = sorted({r.version_spec for r in reqs})
    repo_ids = sorted({r.repo_id for r in reqs})

    parsed: list[tuple[str, VersionRange]] = []
    for spec in specs:
        rng = parse_range(spec)
        if rng is not None:
            parsed.append((spec, rng))
    if not parsed:
        raise VersionConflict(coord_key, specs, repo_ids, "no spec could be parsed")

    combined = VersionRange()
    for _spec, rng in parsed:
        combined = combined.intersect(rng)
    if combined.is_empty:
        raise VersionConflict(
            coord_key, specs, repo_ids, "the specs' intersection is empty (no version satisfies "
            "every declared bound)"
        )

    # Candidates are the versions actually declared as lower bounds — the values that reach
    # `bazel_dep(version = …)`. MVS picks the smallest of them that satisfies every spec, which
    # is `combined.lower` whenever that bound is inclusive.
    candidates = sorted(
        {(rng.lower, rng.lower_text) for _s, rng in parsed if rng.lower is not None}
    )
    for version, text in candidates:
        if combined.contains(version) and all(rng.contains(version) for _s, rng in parsed):
            return text
    raise VersionConflict(
        coord_key,
        specs,
        repo_ids,
        "no declared version satisfies every spec (an exclusive or absent lower bound leaves "
        "MVS nothing to select; a pin must be declared explicitly)",
    )


@dataclass(frozen=True, slots=True)
class VersionResolution:
    """MVS's verdict over the whole external surface of a wave."""

    selected: Mapping[str, str] = field(default_factory=dict)
    conflicts: tuple[VersionConflict, ...] = ()

    @property
    def findings(self) -> tuple[GraphFinding, ...]:
        return tuple(c.as_finding() for c in self.conflicts)

    @property
    def ok(self) -> bool:
        return not self.conflicts

    def require_resolved(self) -> Mapping[str, str]:
        """Rule 11: the first unresolved conflict is raised rather than rendered around."""
        if self.conflicts:
            raise self.conflicts[0]
        return self.selected


def reconcile_versions(requirements: Sequence[VersionRequirement]) -> VersionResolution:
    """§3.3 step 3 over every coordinate at once, collecting conflicts instead of stopping.

    Collected, not raised, because one unsatisfiable coordinate must not hide the other four in
    the same wave — the operator wants the whole list before invoking `conflict_resolution`.
    `require_resolved()` is the fail-loud edge for callers that must not proceed.
    """
    selected: dict[str, str] = {}
    conflicts: list[VersionConflict] = []
    for coord_key, reqs in sorted(_grouped(requirements).items()):
        try:
            selected[coord_key] = mvs_select(coord_key, reqs)
        except VersionConflict as conflict:
            conflicts.append(conflict)
    return VersionResolution(selected=selected, conflicts=tuple(conflicts))


@runtime_checkable
class OverrideProposal(Protocol):
    """The `conflict_resolution` role's output, structurally (`VersionConflictResolution`, §7.7).

    A `Protocol` so this module does not import the LLM package to validate the LLM: the
    validator is the thing that must keep working when the model is wrong.
    """

    @property
    def coord_key(self) -> str: ...
    @property
    def proposed_version(self) -> str: ...
    @property
    def mechanism(self) -> str: ...
    @property
    def violated_specs(self) -> tuple[str, ...]: ...


@dataclass(frozen=True, slots=True)
class OverrideDecision:
    """Code's verdict on a model's pin. `accepted` is the only thing a caller may act on."""

    accepted: bool
    coord_key: str
    version: str
    mechanism: str
    violated: tuple[str, ...] = ()
    """Specs this pin actually breaks — recomputed here, never read from the proposal."""
    undisclosed: tuple[str, ...] = ()
    """Violations the model did not declare. Non-empty ⇒ rejected: a pin whose damage is
    understated reaches a reviewer as safe."""
    reason: str = ""


def validate_override(
    proposal: OverrideProposal, requirements: Sequence[VersionRequirement]
) -> OverrideDecision:
    """Re-derive the proposal's consequences against **every** contributing spec (§7.7).

    On an empty intersection every pin violates something, so "violates a spec" cannot itself be
    the rejection rule — the rule is *disclosure*: the specs the pin breaks are recomputed here
    and compared with `violated_specs`. Anything the model failed to declare rejects the
    proposal. Also rejected: a mechanism outside the two constructs `render_module_bazel` can
    emit, a version that does not parse, and a pin for a coordinate nobody asked about — each of
    which would otherwise be written into `MODULE.bazel` verbatim.
    """
    reqs = [r for r in requirements if r.coord_key == proposal.coord_key]
    if not reqs:
        return OverrideDecision(
            False, proposal.coord_key, proposal.proposed_version, proposal.mechanism,
            reason="no requirement names this coordinate; the pin has no contributing specs",
        )
    if proposal.mechanism not in OVERRIDE_MECHANISMS:
        return OverrideDecision(
            False, proposal.coord_key, proposal.proposed_version, proposal.mechanism,
            reason=f"mechanism must be one of {sorted(OVERRIDE_MECHANISMS)}",
        )
    parsed_pin = parse_range(proposal.proposed_version)
    if parsed_pin is None or parsed_pin.lower is None:
        return OverrideDecision(
            False, proposal.coord_key, proposal.proposed_version, proposal.mechanism,
            reason="proposed_version is not an exact version this module can render",
        )
    pin = parsed_pin.lower

    violated: list[str] = []
    unparsed: list[str] = []
    for spec in sorted({r.version_spec for r in reqs}):
        rng = parse_range(spec)
        if rng is None:
            unparsed.append(spec)
        elif not rng.contains(pin):
            violated.append(spec)
    if unparsed:
        return OverrideDecision(
            False, proposal.coord_key, proposal.proposed_version, proposal.mechanism,
            violated=tuple(violated),
            reason=f"cannot verify the pin against unparseable specs {unparsed}",
        )
    undisclosed = tuple(sorted(set(violated) - set(proposal.violated_specs)))
    if undisclosed:
        return OverrideDecision(
            False, proposal.coord_key, proposal.proposed_version, proposal.mechanism,
            violated=tuple(violated), undisclosed=undisclosed,
            reason="the pin violates specs the proposal did not disclose",
        )
    return OverrideDecision(
        True, proposal.coord_key, proposal.proposed_version, proposal.mechanism,
        violated=tuple(violated),
        reason="every violated spec was disclosed" if violated else "satisfies every spec",
    )


def resolve_workspace_deps(
    deps: Sequence[WorkspaceDep], selected: Mapping[str, str]
) -> tuple[WorkspaceDep, ...]:
    """Stamp MVS's winner onto each `WorkspaceDep.resolved_version` (§5.6)."""
    out: list[WorkspaceDep] = []
    for dep in deps:
        version = selected.get(dep.coordinate.key)
        out.append(dep if version is None else dep.model_copy(update={"resolved_version": version}))
    return tuple(out)


# =======================================================================================
# MODULE.bazel
# =======================================================================================


def _split_extension(extension: str) -> tuple[str, str]:
    """`maven.install` → (`maven`, `install`). The proxy variable and the tag class."""
    var, _, tag = extension.partition(".")
    if not var or not tag:
        raise ValueError(
            f"extension id {extension!r} must be '<extension>.<tag_class>' (e.g. maven.install)"
        )
    return var, tag


def _registry_extension_bzls() -> Mapping[str, str]:
    """The adapters' `use_extension` label table, imported at CALL time.

    Imported here rather than at module import so `bazel/` keeps no import-time dependency on the
    adapter registry, and so this module stays testable with an injected map. It is a *lookup of
    adapter-declared data*, not language knowledge: no `Ecosystem` member, no rule name and no
    directory is named in this file, which is what §13 row 6 forbids.

    The alternative — the drivers threading a map down to every call — is what the
    `@<ruleset>//:extensions.bzl` guess was standing in for: no caller in `src/` ever passed one,
    so the guess was what shipped, and it names a file that exists in one of the seven rulesets.
    """
    from fleet.ecosystems import extension_bzls

    return extension_bzls()


def _registry_ruleset_repo_names() -> dict[str, str]:
    """The adapters' module-name → apparent-repo-name table, imported at CALL time.

    Same shape and same reason as `_registry_extension_bzls` above: which name a ruleset asks its
    dependents to spell it with is per-ruleset knowledge that §13 row 6 keeps out of `bazel/`,
    and an injected map keeps this module testable without the registry.
    """
    from fleet.ecosystems import ruleset_repo_names

    return ruleset_repo_names()


def _load_repo(label: str) -> str | None:
    """The apparent repo a `load()` label reads from: `@aspect_rules_js//js:defs.bzl` →
    `aspect_rules_js`. `None` for a label that names no repo at all.

    A package-relative `//tools:defs.bzl` and a same-repo `:defs.bzl` name the main repository,
    which needs no `bazel_dep`; `@@rules_python+//…` is the canonical form and folds to the same
    name as its apparent one for our purposes, which is why both `@` prefixes are stripped.
    """
    if not label.startswith("@"):
        return None
    return label.lstrip("@").partition("//")[0] or None


def _tag_attrs(
    attrs: Mapping[str, str | list[str]], fallback: Mapping[str, str]
) -> dict[str, str | int | bool | list[str]]:
    """An adapter's `attrs` are the dialect and are rendered verbatim; the fallback is used only
    when the adapter declared none, so no ecosystem-specific attribute name is invented here."""
    if attrs:
        return dict(attrs)
    return dict(fallback)


def _bazel_dep(module: str, version: str, repo_name: str | None) -> str:
    """One `bazel_dep` line, carrying `repo_name` only where the apparent name differs.

    The apparent name is what every `load()` of that ruleset must spell, and a module is visible
    under its MODULE name unless the dependent says otherwise — so this argument is the only
    thing standing between a generator that writes `@io_bazel_rules_go` and a root module that
    knows the repo as `@rules_go`.
    """
    line = f"bazel_dep(name = {_render_scalar(module)}, version = {_render_scalar(version)}"
    if repo_name is not None and repo_name != module:
        line += f", repo_name = {_render_scalar(repo_name)}"
    return line + ")"


def render_module_bazel(
    workspace_deps: Sequence[WorkspaceDep],
    *,
    module_name: str,
    ruleset_versions: Mapping[str, str],
    module_version: str = "0.0.0",
    toolchains: Sequence[ToolchainRequirement] = (),
    targets: Sequence[BuildTarget] = (),
    single_version_overrides: Mapping[str, str] | None = None,
    extension_bzl: Mapping[str, str] | None = None,
    ruleset_repo_names: Mapping[str, str] | None = None,
    header: str = GENERATED_HEADER,
) -> str:
    """The whole `MODULE.bazel`: one `bazel_dep` per ruleset, one tag call per dep (§3.3 step 3).

    Every requirement is recorded, and Bazel's MVS does the selecting for the *artifacts* — which
    is why there is no "pick a winner" branch here. `single_version_overrides` carries the
    *validated* output of `validate_override` and nothing else: an unvalidated pin has no path
    into this function. A ruleset with no pinned version in `build.ruleset_versions` (§9) is a
    hard error, because an unpinned `bazel_dep` resolves differently on the next run.

    **The rulesets are PINNED, and the pin is `single_version_override` (§9).** `bazel_dep(version
    = X)` is an MVS *lower bound*, not a pin: real Bazel selected `rules_python@1.7.0` for a
    configured `1.0.0`, because a transitive module in BCR declared a higher floor. §9's
    reproducibility guarantee is that two runs of the same fleet build the same bytes, and a floor
    that any unrelated BCR publication can raise does not provide it — the monorepo's Python rules
    would change under the fleet with no diff anywhere in this repository. So every ruleset the
    adapters name gets `single_version_override(module_name = …, version = …)` beside its
    `bazel_dep`, and `build.ruleset_versions` means what its name and its docs say.

    A validated conflict-resolution override for the same module name WINS over the configured
    pin: it went through `validate_override` against every contributing spec, and emitting both
    would be a duplicate `single_version_override`, which Bazel rejects outright.

    `extension_bzl` maps a `use_extension` proxy name to the `.bzl` label its ruleset ships it in.
    Default `None` reads the adapters' own table; a var that neither the caller nor the registry
    can place raises, because the alternative is a plausible-looking label that dies inside
    Bazel's loader with a message that points at the ruleset instead of at us (Rule 11).

    **`targets` is what a `load()` needs, and a dependency nobody declared is still a dependency.**
    The ruleset set was once `{d.ruleset for d in workspace_deps} | {t.ruleset for t in toolchains}`
    — the rulesets someone *declared*. A repo whose only claim on a ruleset is that one of its
    targets loads a rule out of it (a package with no external npm coordinates and a `js_binary`
    loading `@aspect_rules_js//js:defs.bzl`) got no `bazel_dep` at all, and real Bazel answered
    `Unable to find package for @@[unknown repo 'aspect_rules_js' …]//js:defs.bzl`. So the
    targets' `load_from` labels contribute too.

    A load-derived name is admitted **only when `ruleset_versions` pins it**, and that is not
    laziness about the missing-pin error: a load label carries an *apparent repo* name, which is
    not a module name. `rules_go` publishes itself as `@io_bazel_rules_go` and `rules_java` is
    injected by Bazel itself, so `bazel_dep(name = "io_bazel_rules_go")` names nothing in any
    registry and raising on it would break every Go repo in the fleet. The pin is the operator's
    statement that a name *is* one of this monorepo's rulesets; declared rulesets still hard-error
    when unpinned, because there the adapter told us it is a module. A pinned ruleset that nothing
    depends on is still not emitted — `bazel_dep` follows use, never the configuration table.

    **`ruleset_repo_names` is the other half of that same split, and it is what makes the apparent
    name TRUE instead of merely tolerated.** Knowing that `@io_bazel_rules_go` is not a module
    name kept a bogus `bazel_dep` out of the file; it did not put the repo in scope, and nothing
    else did either — so every Go package the delegated generator wrote, each loading
    `@io_bazel_rules_go//go:def.bzl`, failed to LOAD under real Bazel (`No repository visible as
    '@io_bazel_rules_go' from main repository`), for the whole ecosystem at once. A module's
    apparent name is set by the DEPENDENT's `bazel_dep(repo_name = …)` and by nothing the module
    itself declares, so it is emitted here, from the adapters' own table (`None` reads the
    registry, as `extension_bzl` does). Only where the two names differ: `repo_name` equal to the
    module name is noise, and every other ruleset in the table is spelled as it is published.
    """
    overrides = dict(single_version_overrides or {})
    bzl_for = dict(_registry_extension_bzls() if extension_bzl is None else extension_bzl)
    repo_name_for = dict(
        _registry_ruleset_repo_names() if ruleset_repo_names is None else ruleset_repo_names
    )

    declared = {d.ruleset for d in workspace_deps} | {t.ruleset for t in toolchains}
    loaded = {
        repo
        for target in targets
        if target.load_from is not None
        for repo in (_load_repo(target.load_from),)
        if repo is not None
    }
    rulesets = sorted(declared | (loaded & set(ruleset_versions)))
    missing = [r for r in sorted(declared) if r not in ruleset_versions]
    if missing:
        raise ValueError(
            f"build.ruleset_versions pins no version for {missing}; an unpinned bazel_dep is a "
            "build that resolves differently on the next run (§9)"
        )
    unresolved = sorted(
        {d.coordinate.key for d in workspace_deps if d.resolved_version is None and not d.attrs}
    )
    if unresolved:
        raise ValueError(
            f"{unresolved} reached MODULE.bazel rendering with no resolved_version; §3.3 step 3 "
            "reconciliation must run first (Rule 11: fail loud)"
        )

    chunks: list[str] = [header.rstrip("\n")]
    chunks.append(
        "module(\n"
        f"{_INDENT}name = {_render_scalar(module_name)},\n"
        f"{_INDENT}version = {_render_scalar(module_version)},\n"
        ")"
    )
    chunks.append(
        "\n".join(_bazel_dep(r, ruleset_versions[r], repo_name_for.get(r)) for r in rulesets)
        if rulesets
        else ""
    )
    pins = {r: ruleset_versions[r] for r in rulesets} | overrides
    if pins:
        chunks.append(
            "\n".join(
                f"single_version_override(module_name = {_render_scalar(name)}, "
                f"version = {_render_scalar(pins[name])})"
                for name in sorted(pins)
            )
        )

    grouped: dict[tuple[str, str], list[str]] = {}
    repos: dict[str, set[str]] = {}
    for dep in sorted(workspace_deps, key=lambda d: (d.ruleset, d.extension, d.coordinate.key)):
        var, tag = _split_extension(dep.extension)
        attrs = _tag_attrs(
            dep.attrs,
            {"name": dep.coordinate.name, "version": dep.resolved_version or ""},
        )
        lines = [f"{var}.{tag}("]
        for key in sorted(attrs):
            lines += _render_attr(key, attrs[key])
        lines.append(")")
        grouped.setdefault((dep.ruleset, var), []).append("\n".join(lines))
        repos.setdefault(var, set()).add(dep.repo_name)
    for toolchain in sorted(toolchains, key=lambda t: (t.ruleset, t.extension, t.name)):
        var, tag = _split_extension(toolchain.extension)
        attrs = _tag_attrs(
            dict(toolchain.attrs), {"name": toolchain.name, "version": toolchain.version}
        )
        lines = [f"{var}.{tag}("]
        for key in sorted(attrs):
            lines += _render_attr(key, attrs[key])
        lines.append(")")
        grouped.setdefault((toolchain.ruleset, var), []).append("\n".join(lines))
        # A tag call CREATES repos; `use_repo` is what makes them visible to the root module, and
        # nothing else does. Without it `@npm_typescript` is `no such package '@@[unknown repo
        # 'npm_typescript' requested from @@]//'` — the same import the `workspace_deps` loop above
        # has always emitted, for the half of MODULE.bazel that never had it.
        repos.setdefault(var, set()).update(toolchain.repo_names)

    for ruleset, var in sorted(grouped):
        bzl = bzl_for.get(var)
        if bzl is None:
            raise ValueError(
                f"{ruleset}: no .bzl label is registered for the module extension {var!r}; the "
                f"adapter that names it must declare it in `extension_bzl` (Rule 11: a guessed "
                f"label fails inside Bazel's loader, pointing at the ruleset instead of at us)"
            )
        block = [f"{var} = use_extension({_render_scalar(bzl)}, {_render_scalar(var)})"]
        block += sorted(set(grouped[(ruleset, var)]))
        for repo_name in sorted(repos.get(var, set())):
            block.append(f"use_repo({var}, {_render_scalar(repo_name)})")
        chunks.append("\n".join(block))

    return "\n\n".join(chunk for chunk in chunks if chunk) + "\n"
