"""The Pydantic v2 data-contract layer (SPEC §5, ADR-0002).

Every object that crosses a process, subagent, LLM or disk boundary is defined here. This
package is fully implemented and has no third-party dependency beyond Pydantic itself.
"""

from __future__ import annotations

from fleet.models.base import LOG_TAIL_BYTES, FleetModel, TruncatedStr, utcnow
from fleet.models.build import (
    BuildPlan,
    BuildTarget,
    BuildUnit,
    GazelleConfig,
    SupportFile,
    ToolchainRequirement,
    WorkspaceDep,
)
from fleet.models.enums import (
    ALLOWED_TRANSITIONS,
    CONTRACT_EDGE_KINDS,
    EQUIVALENCE_RANK,
    KIND_RANK,
    OPERATOR_REOPEN,
    TERMINAL_STATUSES,
    ApproachChangeKind,
    BreakStrategy,
    ContextPolicy,
    ContractKind,
    ContractStatus,
    Ecosystem,
    EdgeKind,
    Equivalence,
    FailureClass,
    ModelTier,
    NodeKind,
    Phase,
    PrState,
    RepoStatus,
    StructuredOutputMode,
    StubFidelity,
    StubState,
    SymbolKind,
    TaskKind,
    TransformTier,
    transition,
)
from fleet.models.graph import (
    DAG_EDGE_KINDS,
    CollisionFinding,
    ContractId,
    ContractNode,
    CycleFinding,
    DependencyEdge,
    EdgeKey,
    GraphNode,
    MigrationWave,
    NodeId,
    SccId,
    SymbolRef,
)
from fleet.models.repo import (
    Coordinate,
    ManifestRef,
    RawDependency,
    RepoId,
    RepoRecord,
    Sha1,
)
from fleet.models.state import SCHEMA_VERSION, MigrationState, PhaseRecord, RepoState
from fleet.models.tasks import (
    DEFAULT_LADDER,
    MAX_ATTEMPTS,
    BackendTarget,
    BuildAttempt,
    FilePatch,
    LlmCallRecord,
    ModelCapabilities,
    Price,
    PullRequestDraft,
    RejectedApproach,
    StubRecord,
    TokenUsage,
    TransformResult,
    TransformTask,
    VerificationReport,
)

__all__ = [
    "ALLOWED_TRANSITIONS",
    "CONTRACT_EDGE_KINDS",
    "DAG_EDGE_KINDS",
    "DEFAULT_LADDER",
    "EQUIVALENCE_RANK",
    "KIND_RANK",
    "LOG_TAIL_BYTES",
    "MAX_ATTEMPTS",
    "OPERATOR_REOPEN",
    "SCHEMA_VERSION",
    "TERMINAL_STATUSES",
    "ApproachChangeKind",
    "BackendTarget",
    "BreakStrategy",
    "BuildAttempt",
    "BuildPlan",
    "BuildTarget",
    "BuildUnit",
    "CollisionFinding",
    "ContextPolicy",
    "ContractId",
    "ContractKind",
    "ContractNode",
    "ContractStatus",
    "Coordinate",
    "CycleFinding",
    "DependencyEdge",
    "Ecosystem",
    "EdgeKey",
    "EdgeKind",
    "Equivalence",
    "FailureClass",
    "FilePatch",
    "FleetModel",
    "GazelleConfig",
    "GraphNode",
    "LlmCallRecord",
    "ManifestRef",
    "MigrationState",
    "MigrationWave",
    "ModelCapabilities",
    "ModelTier",
    "NodeId",
    "NodeKind",
    "Phase",
    "PhaseRecord",
    "PrState",
    "Price",
    "PullRequestDraft",
    "RawDependency",
    "RejectedApproach",
    "RepoId",
    "RepoRecord",
    "RepoState",
    "RepoStatus",
    "SccId",
    "Sha1",
    "StructuredOutputMode",
    "StubFidelity",
    "StubRecord",
    "StubState",
    "SupportFile",
    "SymbolKind",
    "SymbolRef",
    "TaskKind",
    "TokenUsage",
    "ToolchainRequirement",
    "TransformResult",
    "TransformTask",
    "TransformTier",
    "TruncatedStr",
    "VerificationReport",
    "WorkspaceDep",
    "transition",
    "utcnow",
]
